### ISSUE TITLE
[Bug]: native:install fails on npm dependency install

### ISSUE THREAD

**Issue by nagyrobert0213** [NativePHP/laravel#10]
### What happened?

When I run the **php artisan native:install** command, the install fails after the first step

<img width="693" alt="Képernyőfotó 2023-07-20 - 22 26 57" src="https://github.com/NativePHP/laravel/assets/40000524/37485c7c-f797-495c-a20d-55e7f0644307">

### How to reproduce the bug

Run php artisan native:install command, yes after the first prompt

### Package Version

0.1.0

### PHP Version

8.1.17

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

**Comment by blessedjasonmwanza** [comment]
Mine passes, however, It takes forever to run and it gets stuck when starting the electron app. See the screenshot below;

![image](https://github.com/NativePHP/laravel/assets/35315311/f23bc839-0b9e-4338-920c-ef585ea7773c)

**Comment by blessedjasonmwanza** [comment]
> Mine passes, however, It takes forever to run and it gets stuck when starting the electron app. See the screenshot below;
> 
> ![image](https://user-images.githubusercontent.com/35315311/255008322-f23bc839-0b9e-4338-920c-ef585ea7773c.png)

It's stack here for 30 minutes. I am running on Dell Latitude 3400 with intel core i5 8th gen processor.
