### ISSUE TITLE
[Question]: MenuBar not working on Ubuntu ? 

### ISSUE THREAD

**Issue by JibayMcs** [NativePHP/laravel#102]
### What happened?

Hi ! 👋👋

I wonder if it's normal that the MenuBar window doesn't appear when you click on the icon in the top bar?

I assume this is because the Linux version of NativePHP is recent.

Please confirm!

Best regards.

Some details below:

**NativeAppServiceProvider.php**
```php
 MenuBar::create()
            ->icon(public_path('images/menuBarIcon@2x.png'))
            ->route('menubar.index')
            ->width(300)
            ->height(300)
            ->withContextMenu(
                Menu::new()
                    ->quit()
            )->alwaysOnTop();
```

<details>
<summary><b>Demo on click dock icon</b> (gif)</summary>

![Capture vidéo du 01-08-2023 10 05 06](https://github-production-user-asset-6210df.s3.amazonaws.com/7621593/257447538-5921668b-d53d-4848-a5a5-91166bb7ffaa.gif)

</details>

**Ubuntu Version**
```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

<details>
  <summary><b>Console log</b> (<code>php artisan native:serve</code>)</summary>

```bash
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.4.7 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 135ms.

build the electron main process successfully

-----

vite v4.4.7 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 20ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

API server started on port 4000

Starting PHP server... /home/jibaymcs/Documents/Programmation/steadhome/vendor/nativephp/electron/resources/js/resources/php/php artisan serve /home/jibaymcs/Documents/Programmation/steadhome

Making sure app folders are available

Skipping Database migration while in development.
You may migrate manually by running: php artisan native:migrate

PHP Server started on port:  8100

APPIMAGE env is not defined, current application is not an AppImage

checkForUpdatesAndNotify called, downloadPromise is null
```
</details>

### How to reproduce the bug

Nothing appens while clicking the dock/top bar app icon

### Package Version

0.3.3

### PHP Version

8.2.0

### Laravel Version

10.10

### Node Version

18.17.0

### Which operating systems does with happen with?

Linux

**Comment by lothereus** [comment]
same problem. (Ubuntu 22)

adding onlyShowContextMenu() on your MenuBar make the icon response to click (left or right)

**Comment by harshrana-bvi** [comment]
Same Problem, but on Double click it opens, but not changes Icon on the top bar and left side menu doc.
You can check this image for reference [](https://nimb.ws/kie7PO)

**Comment by kalimputhawala** [comment]
For MenuBar at the top of the file use 
use Native\Laravel\Facades\MenuBar;
For Menu use
use Native\Laravel\Menu\Menu;

**Comment by lon9man** [comment]
Hello, has anyone tested function `label` for `MenuBar` in Ubuntu? 
i don't see any text added using `->label('text)` near the icon as on screenshots for MacOS

**Comment by code05-hello** [comment]
Hi There!

I was also having same issue!

`<?php

namespace App\Providers;

use Native\Laravel\Facades\Window;
use Native\Laravel\Contracts\ProvidesPhpIni;
use Native\Laravel\Facades\MenuBar;
use Native\Laravel\Dialog;
use Native\Laravel\Menu\Menu;
use Native\Laravel\Facades\Notification;


use Native\Laravel\Facades\GlobalShortcut;




class NativeAppServiceProvider implements ProvidesPhpIni
{
    /**
     * Executed once the native application has been booted.
     * Use this method to open windows, register global shortcuts, etc.
     */
    public function boot(): void
    {
        // Window::open()
        //            ->width(800)
        //            ->height(800);



        // MenuBar::create()
        //     ->icon(storage_path('/app/menuBarIconTemplate.png'))
        //     ->withContextMenu(
        //             Menu::new()
        //                 ->label('My Application')
        //                 ->separator()
        //                 ->link('https://nativephp.com', 'Learn more…')
        //                 ->separator()
        //                 ->quit()
        //         )
        //     ->route('home')
        //     ->url('https://google.com')
        //     ->label('Status: Online')
        //     ->showDockIcon()
        //     ->show();


        Menu::new()
                   ->appMenu()
                   ->submenu('NativePHP', Menu::new()
                       ->link('https://nativephp.com', 'Documentation')
                   )
                   ->register();
                   // Menu::new()
                   //     ->appMenu()
                   //     ->editMenu()
                   //     ->viewMenu()
                   //     ->windowMenu()
                   //     ->register();

               Window::open()
               ->width(800)
                   ->height(800);

// Notification::title('Hello from NativePHP')
//     ->message('This is a detail message coming from your Laravel app.')
    // ->show();

    // GlobalShortcut::key('Cmd+Shift+I')
    //     ->unregister();

            // Dialog::new()
            //     ->title('Select a file')
            //     ->open();

    }

    /**
     * Return an array of php.ini directives to be set.
     */
    public function phpIni(): array
    {
        return [
                   'memory_limit' => '512M',
                   'display_errors' => '1',
                   'error_reporting' => 'E_ALL',
                   'max_execution_time' => '0',
                   'max_input_time' => '0',
           ];
    }
}
`
