### ISSUE TITLE
[Bug]: A Javascript Error Occured In The Main Process.

### ISSUE THREAD

**Issue by MotionPhix** [NativePHP/laravel#105]
### What happened?

I cannot launch the app on `php artisan native:serve` as an error saying

### A Javascript error occurred in the main process
Uncaught Exception:
Error:spawn \vendor\nativephp\electron\resources\js\resources\php\php
ENOENT

occures everytime. It just gets stuck on the error and nothing else happens.

### How to reproduce the bug

I just created a new Laravel 10 app and then added Nativephp 0.3. After that I run `php` artisan native:serve` then the error above shows up on Windows 11

### Package Version

0.3.0

### PHP Version

8.1

### Laravel Version

10.10

### Node Version

18.8

### Which operating systems does with happen with?

Windows

**Comment by simonhamp** [comment]
Have you run `php artisan native:install`

**Comment by basst85** [comment]
Looks like the same issue as described here: https://github.com/NativePHP/laravel/issues/96

**Comment by ankitkabra-bacancy** [comment]
I face the same but fixed by : https://github.com/NativePHP/electron/issues/69

**Comment by Itz-maanii** [comment]
> I face the same but fixed by : https://github.com/NativePHP/electron/issues/69

I can not find the content of link provided.

**Comment by ankitkabra-bacancy** [comment]
> > I face the same but fixed by : https://github.com/NativePHP/electron/issues/69
> 
> I can not find the content of link provided.

Basically electron issue tab has been moved here therefore link is not working. 

To fix this visit => vendor\nativephp\electron\resources\js\electron-builder.js

https://paste.laravel.io/6c7100ed-fc2f-4d27-ad06-060d70e793fd

Replace this file 

now run below command in sequence :-

=> php artisan native:install 
=> php artisan native:build win (you qill get error a popup click ok and let complete process).
=> php artisan native:serve 

Yeah ! you will your app running on windows !

**Comment by bagusindrayana** [comment]
> > > I face the same but fixed by : https://github.com/NativePHP/electron/issues/69
> > 
> > 
> > I can not find the content of link provided.
> 
> Basically electron repo. issue tab has been moved here therefore link is not working.
> 
> To fix this visit => vendor\nativephp\electron\resources\js\electron-builder.js
> 
> https://paste.laravel.io/6c7100ed-fc2f-4d27-ad06-060d70e793fd
> 
> Replace this file
> 
> now run below command in sequence :-
> 
> => php artisan native:install => php artisan native:build win (you will get error a popup click ok and let complete process). => php artisan native:serve
> 
> Yeah ! you will your app running on windows !

for my case i just change `const isWindows = process.argv.includes('--win');` to `const isWindows = true;`
i idea why this happen and nativephp cant detect window?

**Comment by wellyrm** [comment]
Both solution (https://github.com/NativePHP/laravel/issues/105#issuecomment-1666423625 and https://github.com/NativePHP/laravel/issues/105#issuecomment-1694188618) tried, and worked on my machine

**Comment by mohamedds-12** [comment]
It builds the app but after installing it doesn't do anything !!

**Comment by jhoanborges** [comment]
> > > I face the same but fixed by : https://github.com/NativePHP/electron/issues/69
> > 
> > 
> > I can not find the content of link provided.
> 
> Basically electron repo. issue tab has been moved here therefore link is not working.
> 
> To fix this visit => vendor\nativephp\electron\resources\js\electron-builder.js
> 
> https://paste.laravel.io/6c7100ed-fc2f-4d27-ad06-060d70e793fd
> 
> Replace this file
> 
> now run below command in sequence :-
> 
> => php artisan native:install => php artisan native:build win (you will get error a popup click ok and let complete process). => php artisan native:serve
> 
> Yeah ! you will your app running on windows !

This should be a PR

**Comment by vipertecpro** [comment]
Isn't that suppose to detect OS automatically ? https://nodejs.org/api/process.html#process_process_platform

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
