### ISSUE TITLE
[Bug]: Discussion links when creating a new issue on this repository don't work

### ISSUE THREAD

**Issue by abishekrsrikaanth** [NativePHP/laravel#106]
### What happened?

Discussion links when creating a new issue on this repository don't work

### How to reproduce the bug

Click New Issue on the Issue List and click on the other options other than Bug Report

### Package Version

NA

### PHP Version

PHP 8.2

### Laravel Version

v10.10

### Node Version

LTS

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
This is fixed
