### ISSUE TITLE
[Bug]: Unexpected error code returned on serve

### ISSUE THREAD

**Issue by parasBisht** [NativePHP/laravel#109]
### What happened?

[8691:0802/054130.481742:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY

[8691:0802/054130.482747:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

The futex facility returned an unexpected error code.

### How to reproduce the bug

Followed the installation steps and tried to install inside the homestead 

### Package Version

0.3.3

### PHP Version

8.1

### Laravel Version

10.10

### Node Version

18.13

### Which operating systems does with happen with?

Linux

### Notes

Linux mint (ubuntu-20.04 disk) homestead(vagrant)

**Comment by parasBisht** [comment]
I think this could be due to VM.

**Comment by blankRSD** [comment]
```
Missing X server or $DISPLAY
```

This error happens when your code wants to draw a graphical window but there are no displays available for it to output. This commonly occurs when trying to open a GUI app when in ssh/docker container or in your case homestead.
