### ISSUE TITLE
[Bug]: after start the NativePHP development server 

### ISSUE THREAD

**Issue by Ali7med** [NativePHP/laravel#114]
### What happened?

after start the NativePHP development server

![image](https://github.com/NativePHP/laravel/assets/10943632/f24594bc-1737-4421-b874-690e03606027)

### How to reproduce the bug

after start the NativePHP development server

### Package Version

2.0

### PHP Version

8.2

### Laravel Version

10.17

### Node Version

18.17

### Which operating systems does with happen with?

Windows

**Comment by amitappaspect** [comment]
@Ali7med did any one find solution for this @mpociot . Or Native PHP is sill no support in Windows OS?

**Comment by basst85** [comment]
A temp fix for this error:

You can change this part in electron-builder.js: https://github.com/NativePHP/electron/pull/68/commits/4b316176fdacf1c499d8cf30368f793e420a6712

And then run ``php artisan native:serve`` again.

**Comment by lepresk** [comment]
> A temp fix for this error:
> 
> You can change this part in electron-builder.js: [NativePHP/electron@4b31617](https://github.com/NativePHP/electron/commit/4b316176fdacf1c499d8cf30368f793e420a6712)
> 
> And then run `php artisan native:serve` again.
> 
> Also check this report, this is the cause of the error: #96

https://github.com/NativePHP/electron/commit/4b316176fdacf1c499d8cf30368f793e420a6712 confirm that this fix the error

**Comment by adrianpaiva1** [comment]
same issue on ubuntu 22.04, this temp fix above solves it for me as well.

**Comment by gitnyasha** [comment]
> A temp fix for this error:
> 
> You can change this part in electron-builder.js: [NativePHP/electron@4b31617](https://github.com/NativePHP/electron/commit/4b316176fdacf1c499d8cf30368f793e420a6712)
> 
> And then run `php artisan native:serve` again.
> 
> Also check this report, this is the cause of the error: #96

Thank you this works for me

**Comment by simonhamp** [comment]
This fix has been applied along with others that improve Windows support dramatically.

Please update to nativephp/electron v0.6 and try again.
