### ISSUE TITLE
[Bug]: Error when run command php artisan native:serve

### ISSUE THREAD

**Issue by friczky** [NativePHP/laravel#118]
### What happened?

I get error at `start electron app` when run command `php artisan native:serve` 

### How to reproduce the bug

I send picture on the bottom

### Package Version

0.1.0

### PHP Version

8.1

### Laravel Version

10.15.0

### Which operating systems does with happen with?

Ubuntu 23.04

### Notes

<a href="https://ibb.co/TLnVtd8"><img src="https://i.ibb.co/TLnVtd8/image.png" alt="image" border="0"></a>

**Comment by mpociot** [comment]
Closing this as Linux is not yet officially supported.
