### ISSUE TITLE
[Bug]: sh: 1: cross-env: Permission denied

### ISSUE THREAD

**Issue by liamh101** [NativePHP/laravel#119]
### What happened?

Running `php artisan native:publish`, when reaching  `NativePHP@1.0.0 publish:mac-arm` 

The command `cross-env npm run build && cross-env electron-builder -p always --mac --config --arm64 -p always` is attempted. 

However error message `sh: 1: cross-env: Permission denied` is given.

### How to reproduce the bug

Below is an example dockerfile with the exact base image and commands used to replicate this issue.

```
FROM --platform=linux/amd64 php:8.2.5-fpm

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --2
RUN curl -sL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get -y install nodejs
RUN npm install --global yarn


ARG USER_ID=1000
ARG GROUP_ID=1000

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
RUN usermod -aG www-data user


USER user
```

The `user` user runs all NativePHP's install and publish commands. I realise it's trying to install a Mac version, but it shouldn't stop the build from happening. 

### Package Version

0.1.0

### PHP Version

8.2.5

### Laravel Version

10.14.1

### Which operating systems does with happen with?

Linux

**Comment by mpociot** [comment]
Closing this as we don't have official Linux support yet.
