### ISSUE TITLE
[Bug]: Error: spawn Unknown system error -86 on MacOS

### ISSUE THREAD

**Issue by racmve01** [NativePHP/laravel#120]
### What happened?

<img width="1523" alt="Captura de pantalla 2023-07-21 a la(s) 10 03 06 p m" src="https://github.com/NativePHP/electron/assets/87492856/437b4439-5df4-437a-8db7-d9f4ab142d99">

### How to reproduce the bug

When running the artisan native php:serve gives the error...

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3130
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:47:69
    at Generator.next (<anonymous>)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

API server started on port 4000

Starting PHP server... /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/resources/php artisan serve /Users/profile1/Documents/proyectos_laravel/nativephp

Making sure app folders are available

(node:12387) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at callPhp (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:53:38)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:135:9
    at Generator.next (<anonymous>)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:4:12)
    at /Users/profile1/Documents/proyectos_laravel/nativephp/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/server/php.js:118:45
    at new Promise (<anonymous>)
(Use `Electron --trace-warnings ...` to show where the warning was created)

(node:12387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

### Package Version

0.1.0

### PHP Version

8.1.9

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
If you experience this issue please try the following steps from the root of your application:

1. Delete the `vendor` folder
2. Run `composer install`
3. Run `php artisan native:install`

Some things may go awry while we're in alpha and sometimes clearing out and starting from scratch is the simplest fix

**Comment by benjam-es** [comment]
@simonhamp I have just tried that and it didn't change anything. I have tried it with a fresh install of Laravel a few times, and have tried a fresh install, then remove vendor and composer install again

**Comment by benjam-es** [comment]
@PhiloNL solution worked for me 👍

**Comment by simonhamp** [comment]
I'd like to get to the bottom of that... if you're having to install Rosetta, does that mean users will need to when they install your distributed app?

That doesn't feel right

**Comment by mdloop** [comment]
I am 99% sure that the intel binary for php is copied over instead of the arm one when you are on arm. And that's why we've had to install rosetta.

See this https://github.com/NativePHP/laravel/issues/120#issuecomment-1663854783

**Comment by mdloop** [comment]
I'll take a look at see if I can find code that actually does this later tonight.

**Comment by Meyfarth** [comment]
I'm the one who created #58, after deleting the whole vendor file, upgrading to the latest version, `php artisan native:install` then `php artisan native:serve` (with default options / values), it started the app!

Thanks for helping 🙂

**Comment by cfreear** [comment]
Seeing this exact same error on a fresh Laravel install (just for testing nativephp)

Mac Mini M2 Pro 2023 running Venture 13.4.1

**Comment by simonhamp** [comment]
A load of updates to PHP version handling have been made recently.

Please update to nativephp/electron v0.6 and try again.
