### ISSUE TITLE
[Bug]: Issue with Laravel NativePHP Installation on MacOS (Intel x64)

### ISSUE THREAD

**Issue by BurakBoz** [NativePHP/laravel#123]
### What happened?

I'm experiencing a problematic sequence of steps while setting up Laravel's NativePHP on a MacOS architecture with Intel x64. Here are the steps I'm following:

```bash
composer create-project laravel/laravel nativephptest --prefer-dist
cd nativephptest
composer require nativephp/electron
php artisan native:install
```
The issue lies within the second prompt/question during the php artisan native:install process.

The prompt in question is:

`Would you like to start the NativePHP development server (yes/no) [no]:`

When I respond 'yes' to this prompt, the process seems to break before the configuration files are published. This leads to a situation where the application doesn't start if one has not installed and used NativePHP before.

However, when I choose 'no', the installation process completes without any issue. Furthermore, once I successfully installed it once with 'no', subsequent installations did not show any errors, even when I responded 'yes' to the prompt.

My theory is that the issue could be related to the default architecture, which seems to be ARM. This might be causing problems with my Intel-based Mac.

As a suggestion, the problematic question could either be eliminated or moved to a point after the configuration files are published. This might prevent the premature break in the installation process.

Please let me know if further information is required to address this issue.

### How to reproduce the bug

Use fresh Intel mac (no composer packages or nativephp installed)

```bash
composer create-project laravel/laravel nativephptest --prefer-dist
cd nativephptest
composer require nativephp/electron
php artisan native:install
```

Say yes / yes
`Would you like to start the NativePHP development server (yes/no) [no]: yes`

### Package Version

0.1.1

### PHP Version

8.2.6

### Laravel Version

10.15.0

**Comment by simonhamp** [comment]
A whole load of improvements have been made recently.

Please update to nativephp/electron v0.6 and try again.
