### ISSUE TITLE
[Bug]: MenuBar Feature not working

### ISSUE THREAD

**Issue by christophstockinger** [NativePHP/laravel#125]
### What happened?

I created a new Laravel app and installed the package according to the tutorial. Then I tried to create a MenuBar application according to the doc. However, the icon is never displayed in the MenuBar.

### How to reproduce the bug

```php
// in the NativeAppServiceProvider
 MenuBar::create()
            ->width(400)
            ->height(400)
            ->alwaysOnTop()
            ->url('https://christophstockinger.com')
            ->label('Hallo')->open();
```

### Package Version

0.1.0

### PHP Version

8.2.6

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

### Notes

Mac-Book Pro 14" - 2023
Apple M2 Max
macOs 13.2 (22D49)

**Comment by damms005** [comment]
On Zorin OS (based on Ubuntu), the MenuBar icon shows, but clicking it does not reveal its content.

**Comment by simonhamp** [comment]
@damms005 this thread was about Mac. Please open a separate ticket for your Linux issue

**Comment by simonhamp** [comment]
A whole load of improvements have been made recently.

Please update to nativephp/electron v0.6 and try again.
