### ISSUE TITLE
[Bug]: Syntax error in nativephp\electron\resources\js\electron-builder.js

### ISSUE THREAD

**Issue by andreoneres** [NativePHP/laravel#127]
### What happened?

I can't initialize development environment with `php artisan native:serve` command. A syntax error is returned in the file _/nativephp/electron/resources/js/electron-builder.js_

### How to reproduce the bug

When executing the command `php artisan native:serve` the following error is shown:
![Error screenshot.](https://i.imgur.com/FOgX8b3.png)

### Package Version

0.3.0

### PHP Version

8.1

### Laravel Version

10.10.0

### Which operating systems does with happen with?

Windows

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
