### ISSUE TITLE
[Bug]: Running native:serve gives an error regarding SUID sandbox helper.

### ISSUE THREAD

**Issue by RoccoHoward** [NativePHP/laravel#130]
### What happened?

Getting the following error:

```[FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /vendor/nativephp/electron/resources/js/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.```

### How to reproduce the bug

```php artisan native:serve```

### Package Version

0.3.2

### PHP Version

8.2.8

### Laravel Version

10.16.1

### Which operating systems does with happen with?

Windows, Linux

### Notes

The fix is to run ```export npm_config_platform=win32``` before ```php artisan native:serve```

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
