### ISSUE TITLE
[Bug]: Can't paste to input using Cmd+V

### ISSUE THREAD

**Issue by MasterRO94** [NativePHP/laravel#132]
### What happened?

I tried to paste a string to window input and nothing happens. Same view in browser works as expected but in NativePHP window doesn't.

### How to reproduce the bug

Create a window with input and try to paste a string.

### Package Version

0.1.2

### PHP Version

8.1

### Laravel Version

10.15

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
You need to have the Copy-Paste keyboard shortcuts registered via the Edit menu. Try adding `editMenu()` to your main app `Menu` in your NativeAppServiceProvider:

```php
Menu::new()
    ...
    ->editMenu();
```

**Comment by mpociot** [comment]
That's one reason why I removed the example Menu:: calls in the NativeAppServiceProvider that we register by default. 
As Simon said, adding the editMenu will add all the default shortcuts 👍
