### ISSUE TITLE
[Bug]: Application Menu Not visible 

### ISSUE THREAD

**Issue by ankitkabra-bacancy** [NativePHP/laravel#133]
### What happened?

As I tried with fresh laravel 10 installed with node v 20 I tried to built native desktop app in windows 11. I able to up the app but when exploring Application menu section from here [](https://nativephp.com/docs/1/the-basics/application-menu#creating-a-menu)

I just pasted this sample code 

`
Menu::new()
            ->appMenu()
            ->submenu('NativePHP', Menu::new()
                ->link('https://nativephp.com', 'Documentation')
            )
            ->register();
 
Window::open();

`
        
But app is up but the menu is not visible ? can anybuddy or author help me to findout what's the cause of this ?

Laravel verison : 10.10
Node version : 20.5.0
NPM version : 8.3.2
Platform : Windows
OS : Windows 11 22H2 (build 22621.1992)

![image](https://github.com/NativePHP/electron/assets/98305971/86dce29b-317a-4d66-b77b-464cf4921ba6)

        
        

### How to reproduce the bug

- Install fresh laravel 10
- install native php and build the windows build first.
- then serve the native php 
- as per doc just paste the sample code to create menu bar.
- once app is up you will see nothing in application menu.

### Package Version

0.3.2

### PHP Version

8.1.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
