### ISSUE TITLE
[Bug]: Report

### ISSUE THREAD

**Issue by MasterRO94** [NativePHP/laravel#134]
### What happened?

@mpociot Thanks a lot for this amazing tool.

I tried to build a simple MenuBar application with one settings window. I found a couple of bugs.

1. `MenuBar::hide()` method doesn't work for me. 
2. After running `php artisan native:build` I launched the application but MenuBar didn't show, any window didn't opened (settings window should be opened by default) and the Application menu was like it was before changes (eg. default and not my custom). In dev mode running `php artisan native:serve` all works as expected except of `MenuBar::hide()`

Maybe I did something wrong as the documentation does not cover all cases as it's  in alpha.

### How to reproduce the bug

Build a MenuBar app with one window

### Package Version

0.3.2

### PHP Version

8.1

### Laravel Version

10.15

### Which operating systems does with happen with?

macOS

### Notes

I have MacBook on Intel with MacOS 13.4.

**Comment by simonhamp** [comment]
@MasterRO94 please can you separate the 2 separate issues here into separate tickets?

**Comment by simonhamp** [comment]
A whole load of improvements have been made recently.

Please update to nativephp/electron v0.6 and try again.
