### ISSUE TITLE
[Bug]: Failed to build in Ubuntu 22.04.2 LTS (X64)

### ISSUE THREAD

**Issue by divyank420** [NativePHP/laravel#135]
### What happened?

I have installed fresh laravel also I have installed native php then I cannot run the native: serve command and face some errors like :
libstdc++.so.6: version `GLIBCXX_3.4.29' not found 
![Screenshot from 2023-07-31 11-46-01](https://github.com/NativePHP/electron/assets/47395556/d91c5dd2-7770-456a-bd9a-a56febdb1a91)

### How to reproduce the bug

1. Install fresh laravel 10
2. install native php and build the Linux build first.
3. then serve the native PHP

### Package Version

0.3.1

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

**Comment by simonhamp** [comment]
Please update to v0.6.1 and try again
