### ISSUE TITLE
[Bug]: php artisan native:serve - Fails to open native app instance/UI

### ISSUE THREAD

**Issue by blessedjasonmwanza** [NativePHP/laravel#14]
### What happened?

When I run ```php artisan native:serve```, the terminal fails to start the native application as per documentation expectations. Below is a screenshot attached.

Node version;

![image](https://github.com/NativePHP/laravel/assets/35315311/de268e03-f257-49e3-8cfc-676dce31c775)

### How to reproduce the bug

```php artisan native:serve``` gets stuck at node unhandled promise rejection; see screenshot below;

![image](https://github.com/NativePHP/laravel/assets/35315311/bb496503-9b1f-4133-a352-1941730f884b)

### Package Version

0.1.0

### PHP Version

8.2.8

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

**Comment by antonioanerao** [comment]
I`m facing the same. Trying a few things to turn around it

**Comment by mpociot** [comment]
The `app.dock` error is now resolved, but there'll probably be other Linux related issues, as we currently don't distribute PHP binaries for Linux.
