### ISSUE TITLE
[Bug]: Cannot find module 'dmg-license'

### ISSUE THREAD

**Issue by zimbar** [NativePHP/laravel#147]
### What happened?

Hy

I execute this command fo publish "php artisan native:publish" but i have this error Cannot find module 'dmg-license'

### How to reproduce the bug

php artisan native:publish

### Package Version

0.3.2

### PHP Version

8.2.1

### Laravel Version

10.10

### Node Version

18.16.1

### Which operating systems does with happen with?

Linux

**Comment by zimbar** [comment]
hello,

No response ?

**Comment by LTaooo** [comment]
same with you on ubuntu
![image](https://github.com/NativePHP/laravel/assets/28125259/d4579543-edbf-4eaa-b374-652e6b57e4c1)

**Comment by blankRSD** [comment]
When running `native:build` or `native:publish` command nativephp uses cross-compilation by default. Cross-compilation in not supported in linux(you need a mac to build a dmg). 

You can use `php artisan native:publish linux` to be specific about OS.

**Comment by DanteB918** [comment]
![image](https://github.com/NativePHP/laravel/assets/100642899/a7b296c2-9401-472d-87f9-907388d14461)
![image](https://github.com/NativePHP/laravel/assets/100642899/fb455a13-cea9-404b-95ed-419b41b92f64)

@blankRSD , I am using WSL2 on a windows machine, but even specifying Linux as the OS doesn't seem to resolve this issue for me when using `php artisan native:publish linux`

If I use `php artisan native:build linux` , then yes it does seem to work for me.

**Comment by taophp** [comment]
Same as @DanteB918 here on Ubuntu...

**Comment by simonhamp** [comment]
Some of the logic here may not have been working perfectly in older releases.

Please `composer update` and try again. If you're still having issues, please feel free to re-open this ticket.
