### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by korangcity** [NativePHP/laravel#150]
### What happened?

When I run `php artisan native:serve` , I see

 Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

/home/mahdi/Desktop/nativePhp/vendor/nativephp/electron/resources/js/node_modules/vite/dist/node-cjs/publicUtils.cjs:3314
        enabled = !!DEBUG?.includes(ns);
                                        ^

SyntaxError: Unexpected token '.'

### How to reproduce the bug

This problem does not let me to run app

### Package Version

1.0.0

### PHP Version

 8.1.2-1ubuntu2.13

### Laravel Version

10.17.1

### Node Version

v12.22.9

### Which operating systems does with happen with?

Linux

### Notes

How can I fix this problem?

**Comment by joffreycarle** [comment]
A few hints here:
- Maybe update your Node version
- Check if there is any update on `nativephp/electron` package with Composer

**Comment by simonhamp** [comment]
Please update to nativephp/electron v0.6 and try again.
