### ISSUE TITLE
[Bug]: error during start dev server on windows

### ISSUE THREAD

**Issue by pratikkuikel** [NativePHP/laravel#151]
### What happened?

Nativephp development server error on windows.

### How to reproduce the bug

1. Fresh laravel installation 
2. composer require nativephp/electron
3. php artisan native:install
 3.1  Would you like to install the NativePHP NPM dependencies? (yes/no) [yes]:
 - yes
 3.2 Would you like to start the NativePHP development server (yes/no) [no]:
 - yes

### Package Version

^0.3.3

### PHP Version

8.1.0

### Laravel Version

10.10

### Node Version

18.8.0

### Which operating systems does with happen with?

Windows

### Notes

php artisan native:install -v
Publishing NativePHP Service Provider...

 Would you like to install the NativePHP NPM dependencies? (yes/no) [yes]:
 > yes

Fetching latest dependencies…

> NativePHP@1.0.0 postinstall
> node electron-builder install-app-deps

Binary Source:  D:\nativephp\nativephp\vendor/nativephp/php-bin/bin/
Binary Filename:  php
Arch:  x64
Platform:  win32
Copying PHP file(s) from D:\nativephp\nativephp\vendor\nativephp\php-bin\bin\mac\x86 to D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\php
Copied PHP binary to  D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\php
Copied certificate file to D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\cacert.pem

changed 24 packages, and audited 560 packages in 5s

79 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 Would you like to start the NativePHP development server (yes/no) [no]:
 > yes

Starting NativePHP dev server…
Fetching latest dependencies…

> NativePHP@1.0.0 postinstall
> node electron-builder install-app-deps

Binary Source:  D:\nativephp\nativephp\vendor/nativephp/php-bin/bin/
Binary Filename:  php
Arch:  x64
Platform:  win32
Copying PHP file(s) from D:\nativephp\nativephp\vendor\nativephp\php-bin\bin\mac\x86 to D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\php
Copied PHP binary to  D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\php
Copied certificate file to D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\resources\cacert.pem

up to date, audited 560 packages in 3s

79 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.4.7 building for development...

watching for file changes...

build started...
transforming...
✓ 4 modules transformed.
rendering chunks...
out/main/index.js  0.55 kB
built in 693ms.

build the electron main process successfully

-----

vite v4.4.7 building for development...

watching for file changes...

build started...
transforming...
✓ 1 modules transformed.
rendering chunks...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
out/preload/index.js  0.70 kB
built in 39ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
error during start dev server and electron app:
Error: Electron uninstall
    at getElectronPath (D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-e45cc666.js:60:19)
    at Object.startElectron (D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-e45cc666.js:121:26)
    at createServer (D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\chunks\lib-25a7a89c.js:74:21)
    at async CAC.<anonymous> (D:\nativephp\nativephp\vendor\nativephp\electron\resources\js\node_modules\electron-vite\dist\cli.js:48:9)    
NativePHP scaffolding installed successfully.

crypto@DESKTOP-C5UVA7B MINGW64 /d/nativephp/nativephp
$ php artisan native:serve
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

**Comment by NawrasBukhari** [comment]
I can confirm it still exists on version 0.4.0 Windows 11, Laravel 10.10

**Comment by justSatyr** [comment]
Same as above. 0.4.0, Win11, Laravel 10.10

**Comment by t-prod** [comment]
Same thing but I get stucked on this :

0.4.0, Win 11, last Laravel, PHP 8.1.9

![image](https://github.com/NativePHP/laravel/assets/1824638/88c6be14-8e79-46d0-b397-c284e64f6fbd)

The requirements does not include Windows :

![image](https://github.com/NativePHP/laravel/assets/1824638/fb981a80-38aa-4df2-96c4-0ca24df003cd)

Maybe by Docker ?

**Comment by sandy2013** [comment]
I also stuck on same thing, any one can help for the same, please

**Comment by lucaswalmor** [comment]
I also stuck on same thing, windows 11, php 8.2, laravel 10.24, node 18.16.0

**Comment by TranceDevCode** [comment]
i have the same error here, how can fix this error? 
![image](https://github.com/NativePHP/laravel/assets/50996233/da21a0cc-5afc-4ac5-bd88-48bd2501b469)

**Comment by ryanlovett-au** [comment]
Making the changes detailed in the commit here: https://github.com/NativePHP/electron/commit/4b316176fdacf1c499d8cf30368f793e420a6712 resolves this issue on Windows...

**Comment by dynamitedeeps** [comment]
@ryanlovett-au 
it works 
thanks

**Comment by simonhamp** [comment]
Installing NativePHP on Windows has had a few annoying issues which I've recently resolved.

Also, building and publishing for Windows hasn't been officially supported due to the way that PHP was distributed under Windows.

That is until now.

Please update to nativephp/electron v0.6 and try again.
