### ISSUE TITLE
[Bug]: native:install isn't using Linux binary

### ISSUE THREAD

**Issue by liam-wiltshire** [NativePHP/laravel#157]
### What happened?

After installing nativephp on a brand new Laravel install, running `native:serve` throws the following error:

```
Error: Command failed: /home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config
/home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/php/php: /home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/php/php: cannot execute binary file
```

Digging into it a bit further, it appears that, while I'm on Linux, `native:install` copied over the osx PHP binary:

```
Binary Source:  /home/liam/Tools/finance-tools/vendor/nativephp/php-bin/bin/
Binary Filename:  php
Arch:  x64
Platform:  linux
Copying PHP file(s) from /home/liam/Tools/finance-tools/vendor/nativephp/php-bin/bin/mac/x86 to /home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/php
Copied PHP binary to  /home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/php
Copied certificate file to /home/liam/Tools/finance-tools/vendor/nativephp/electron/resources/js/resources/cacert.pem
```

It's detecting the correct Arch and platform, but is still copying over the mac/x86 binary for some reason.

### How to reproduce the bug

New Laravel project `composer create-project....`

Clean NativePHP install `composer require nativephp/electron; php artisan native:install;`

Say yes to everything :) 

### Package Version

0.3.0

### PHP Version

8.1.18

### Laravel Version

10.17.1

### Node Version

20.5.0

### Which operating systems does with happen with?

Linux

**Comment by IvanSerpa** [comment]
I had the same problem, this PR solved the problem for me: https://github.com/NativePHP/electron/pull/57
It is already merged into the main branch, but it was not included in the last release.

**Comment by liam-wiltshire** [comment]
Thanks @IvanSerpa !! Worked after updating to dev-main
