### ISSUE TITLE
[Bug]: Could not resolve from "src/main/index.js"

### ISSUE THREAD

**Issue by joebenson** [NativePHP/laravel#16]
### What happened?

Running `php artisan native:install` gets hung up trying to build for development:

Mac OS Ventura 13.4.1
PHP 8.2.8
Node / NPM (v20.5.0 / v9.8.0)
Yarn 1.22.19
Fresh Laravel app install

![image](https://github.com/NativePHP/laravel/assets/2358654/7512c5cf-e841-4a17-9ef2-717cd8b3677d)

### How to reproduce the bug

Follow the installation steps step-by-step with up-to-date dependencies as described.

### Package Version

0.1.0

### PHP Version

8.2.8

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by phuclh** [comment]
I got the same error.

**Comment by raulillana** [comment]
Same here.

**Comment by Nembie** [comment]
Same problem here, maybe there's something to change in the ```package.json``` under Electron 👀

**Comment by GITSKayDomrose** [comment]
Same here.
Looks like it doesn't copy the php and cert files to `vendor/nativephp/electron/resources/js/out/main`, but i could figure out why.

![Uploading Screenshot 2023-07-21 at 09.55.58.png…]()

**Comment by mpociot** [comment]
This should now be fixed with the latest version(s)
