### ISSUE TITLE
[Bug][laravel]:  ERROR  Command "native:install" is not defined. Did you mean one of these? 

### ISSUE THREAD

**Issue by mina20088** [NativePHP/laravel#17]
### What happened?

i firstly installed the wrapper for Laravel from composer using this command
 ```
   composer require nativephp/laravel
 ```
then i uses this command to publish the native app as the doc say
```
php artisan native:install
```
i got error above and includes the screen shoot
![Screenshot from 2023-07-21 03-07-18](https://github.com/NativePHP/laravel/assets/39167278/3b3d5e2f-c95a-41a9-be19-1f46e01051b1)

 

### How to reproduce the bug

when i used the command 
```
php artisan native:install
```
i saw the below error
![Screenshot from 2023-07-21 03-07-18](https://github.com/NativePHP/laravel/assets/39167278/830c4ee5-8a75-4b08-803f-d853e5d90d81)

### Package Version

0.1.0

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

Linux

### Notes

same thing happens when using the command 
```
php artisan native:serve
```
![Screenshot from 2023-07-21 03-15-30](https://github.com/NativePHP/laravel/assets/39167278/dedfc3f3-a8ad-47fb-aa21-244349fc0365)

**Comment by axyr** [comment]
The documentation is assuming you have an existing laravel app:

```
laravel new my-app

cd my-app

composer require nativephp/laravel

php artisan native:install

```

**Comment by git-e-001** [comment]
![image](https://github.com/NativePHP/laravel/assets/78661753/14fdfc93-664c-4afd-b2a4-390ecd5e0e71)

**Comment by arbazargani** [comment]
i had the same problem, canceling batch job and composer dumpautoload, solved this stucking and then i faced new issue:
node version & etc. updated node version to 20 & still some errors remains & can't run app yet, by the way, maybe dumpautoload helps you pass this step to new errors like me :)

**Comment by mina20088** [comment]
> The documentation is assuming you have an existing laravel app:
> 
> ```
> laravel new my-app
> 
> cd my-app
> 
> composer require nativephp/laravel
> 
> php artisan native:install
> 
> ```

I made a new project o laravel and that's what happens
