### ISSUE TITLE
[Bug]: 'native:migrate fresh' does not work

### ISSUE THREAD

**Issue by ilkermutlu** [NativePHP/laravel#175]
### What happened?

By running `php artisan native:migrate fresh`, I expected the whole database schema to be refreshed and all data gone as explained in the docs.

### How to reproduce the bug

When I run the command, the output is as follows:

`No arguments expected for "native:migrate" command, got "fresh".`

### Package Version

0.4.0

### PHP Version

8.2.8

### Laravel Version

10.18.0

### Node Version

20.5.0

### Which operating systems does with happen with?

macOS

**Comment by mhoffmann777** [comment]
#168

**Comment by blankRSD** [comment]
Use `php artisan migrate:refresh` instead

**Comment by vesper8** [comment]
> Use `php artisan migrate:refresh` instead

If you run this, it will perform the refresh on the local database (mysql for example) and not on the one that NativePhp uses ?
