### ISSUE TITLE
[Question] How to rename Library/Application Support folder

### ISSUE THREAD

**Issue by StanBarrows** [NativePHP/laravel#18]
Currently, when initiating a NativePHP app, a NativePHP folder within your Library/Application Support Folder will be created. Can the folder name be set based on the application name? I assume. Otherwise, there will be a conflict with running multiple NativePHP Applications.

![CleanShot 2023-07-20 at 19 08 33@2x](https://github.com/NativePHP/laravel/assets/10268813/aa034bcd-e776-4bc5-a21f-cde740b0e644)

**Comment by mpociot** [comment]
Yes, this name keeps being "NativePHP" at the moment while running `native:serve`.
As soon as you build your app for production, this will use the actual name of your app.
