### ISSUE TITLE
[Bug]: native:install is too slow

### ISSUE THREAD

**Issue by eskayamadeus** [NativePHP/laravel#186]
### What happened?

I ran ```php artisan native:install``` and it took about 10 minutes to install. At a point, the output was frozen and I had to hit the Enter key to force an update in the terminal.

Also, it did not show the precise output of what specific NPM packages were being installed.

However, it ran without reporting any errors.

![image](https://github.com/NativePHP/laravel/assets/17624113/b347a23c-8057-4f27-b362-5eb379540d5e)

### How to reproduce the bug

Run ```php artisan native:install``` in a fresh Laravel project.

### Package Version

0.4.0

### PHP Version

8.2.7

### Laravel Version

10.19.0

### Node Version

16.13.1

### Which operating systems does with happen with?

Windows

**Comment by JelleTalsma** [comment]
It doesn't support windows yet. [Requirements here](https://nativephp.com/docs/1/getting-started/installation#requirements)

**Comment by vipertecpro** [comment]
Please release windows support first so that all the window users can also participate in finding/resolving bugs. 

Thank you.

**Comment by simonhamp** [comment]
Building and publishing for Windows hasn't been officially supported until now.

Please update to nativephp/electron v0.6 and try again.

**Comment by eskayamadeus** [comment]
> Building and publishing for Windows hasn't been officially supported until now.
> 
> Please update to nativephp/electron v0.6 and try again.

I'll give it a shot. Thanks
