### ISSUE TITLE
[Bug]: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"

### ISSUE THREAD

**Issue by secondmanveran** [NativePHP/laravel#187]
### What happened?

When attempting to build I get the following error:

```bash
vite v4.4.7 building for production...
✓ 3 modules transformed.
✓ built in 60ms
Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/me/Sites/secondman/todo/vendor/nativephp/electron/resources/js/src/main/index.js
error during build:
RollupError: Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"
    at error (file:///Users/me/Sites/secondman/todo/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/me/Sites/secondman/todo/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24674:24)
    at file:///Users/me/Sites/secondman/todo/vendor/nativephp/electron/resources/js/node_modules/rollup/dist/es/shared/node-entry.js:24636:26
```

### How to reproduce the bug

Run:

```bash
php artisan native:build
```

### Package Version

0.4.0

### PHP Version

8.2.8

### Laravel Version

10.19.0

### Node Version

18.17.0

### Which operating systems does with happen with?

macOS

### macOS 13.14.1 (c)

- Processor: 2.3 GHz 8-Core Intel Core i9
- Graphics: AMD Radeon Pro 5500M 8 GB Intel UHD Graphics 630 1536 MB
- Memory: 16 GB 2667 MHz DDR4

In #77 [@Rueff19](https://github.com/Rueff19) resolved this same issue by switching to SQLite, I'm already using SQLite, so this may be related to something else. My application works perfectly, just won't build.

**Comment by JelleTalsma** [comment]
indeed, what "dwedaz" said. you need to run the command `bug, to fix the problem you need to cp -r vendor/nativephp/php-bin/bin/mac/arm64 vendor/nativephp/php-bin/bin/mac/x64` that will make it work

**Comment by secondmanveran** [comment]
Negative. 

This happens automatically during the build, but either way, I already found that online and tried it. This is the current error after using this method.

**Comment by JelleTalsma** [comment]
Allright, it fixed it for me. Could it be that your'e running php 8.2 instead of 8.1? The docs say you need 8.1 specifically i think. You could try that

**Comment by secondmanveran** [comment]
That could be it. Though I can't imagine why that would make a difference. There are no breaking changes between 8.1 and 8.2.

**Comment by dwedaz** [comment]
in my condition, the problem is index.js wants to copy binary file "php" from folder x64, but the vendor does not provide the path.  can you share the full log?

**Comment by secondmanveran** [comment]
@dwedaz 

Yes I mis-read your answer. This did solve the problem. Now if I can just replace this NativePHP icon and fix the context menu I'll be all set.

Thanks.
