### ISSUE TITLE
[Bug]: Let us specify which architecture to build for Mac

### ISSUE THREAD

**Issue by vesper8** [NativePHP/laravel#206]
### What happened?

Currently running the mac build takes incredibly long.. on my M1 Max it takes over 10 minutes. Each time it builds the x64, arm64, and if the log is to be trusted, an x86 version as well? I think the latter is wrong.. but anyway.. for development purposes at least.. I only care about building the arm64 version and nothing else.. please let us skip the other builds so it takes less time to build.

### How to reproduce the bug

See above

### Package Version

0.4.0

### PHP Version

8.2.0

### Laravel Version

10

### Node Version

16

### Which operating systems does with happen with?

macOS

**Comment by Lirux** [comment]
You could do ```php artisan native:build mac-arm```

**Comment by simonhamp** [comment]
@vesper8 did you manage to try this using `native:build Mac-arm`?

**Comment by simonhamp** [comment]
@Lirux @vesper8 I found out when I tried this that simply using `mac-arm` as an argument to the command still produced both the ARM and x64 builds of the Mac app because it was hardcoded into the electron builder config to do so.

I've removed that in the attached PR and that will be released soon
