### ISSUE TITLE
[Bug]: Unable to open built apps on Mac (M1)

### ISSUE THREAD

**Issue by vesper8** [NativePHP/laravel#207]
### What happened?

I followed the tutorial to create the team-time app from here https://laravel-news.com/nativephp-tutorial

The app works well in the browser, and also works well when I do native:share

But when I `native:build mac`, well first it hits this error that everyone else is getting. Running `cp -r vendor/nativephp/php-bin/bin/mac/arm64 vendor/nativephp/php-bin/bin/mac/x64` resolves that error and I get a dist folder with the Laravel.app file in there.

When I try to open it, it says that the app is invalid and that I should move it to the trash

I tried `xattr -r -d com.apple.quarantine /path/to/Laravel.app` and `xattr -cr /path/to/Laravel.app`

None of those too resolve the problem and I am unable to open the app.

Seems the problem is probably due to signing. I do have an Apple Developer account and I can see from the log that it's attempting to sign the app with my account.. not that I would necessarily want this since this is a company account. There should be instructions on how to selfsign for development purposes.. or at least address this problem one way or another.

### How to reproduce the bug

See above

### Package Version

0.4.0

### PHP Version

8.2

### Laravel Version

10

### Node Version

16

### Which operating systems does with happen with?

macOS

**Comment by Loydtafireyi** [comment]
Same issue on M1 mac

**Comment by billriess** [comment]
Seems like the binaries are still outdated and require PHP 8.1.

**Comment by simonhamp** [comment]
I believe this was due to an error in the builder logic moving the incorrect binary file.

Please run `composer update` to get the latest version of `nativephp/electron` and try again.

**Comment by KirillDakhnyuk** [comment]
@simonhamp I experienced quite similar issue when I tried to open published app on the another Mac M1. The modal says: "This application can't be opened". I can open the app on my Mac though. Should I create another issue for that?

**Comment by KirillDakhnyuk** [comment]
@simonhamp sure, I sent dmg file to another Mac, double clicked it and drag the app into the applications. But, I tried to send the app itself from the mac-arm64 folder via AirDrop, and the App act like any unverified app on Mac and after one click it's working.

**Comment by simonhamp** [comment]
Sorry, what do you mean "after one click it's working"?

**Comment by KirillDakhnyuk** [comment]
@simonhamp when you installed an app from the direct web download it could happen that you need to right click on the app's icon and choose "open". That's was the case.

**Comment by simonhamp** [comment]
Ok, so I think this is about notarizing on Mac ([see Apple's documentation](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution))

As I understand it, software won't run on another machine if it has been signed but not notarized.

When it's notarized, if it's shared with another Mac, the user will see a prompt similar to this the first time they try to run the app:

![](https://docs-assets.developer.apple.com/published/ee6161c723/3088610@2x.png)

As I understand things right now, you MUST sign and notarize your app to distribute it to another machine.

I don't yet know if there's a way around this for testing during development purposes, but I highly doubt it as that would defeat the purpose of the whole solution in the first place.

**Comment by KirillDakhnyuk** [comment]
You're correct. Thanks.
Should it be a feature? I guess it would be nice to enter those values in .env.

https://www.electronjs.org/docs/latest/tutorial/code-signing

**Comment by simonhamp** [comment]
[It already is a feature](https://github.com/NativePHP/electron/blob/4f801608400f435de1f07e96a20b82486d094781/resources/js/build/notarize.js#L23-L25), it just isn't in the docs yet.

I'll add this today

**Comment by simonhamp** [comment]
If anyone in this thread is still having trouble, please try updating to v0.6.1 of nativephp/electron.

Building on Mac seems to be working much more reliably in these later versions.

If you do still have issues, please open a new ticket.

**Comment by mraheelkhan** [comment]
Anyone landing here. 
You must add these `.env` variables with correct credentials. 

```
NATIVEPHP_APPLE_ID=abc@icloud.com
NATIVEPHP_APPLE_ID_PASS="yourAppSpecifcPassword"
NATIVEPHP_APPLE_TEAM_ID=YOURTEAMID
```

Helpful links: 
[Generate App Specific Passwords](https://support.apple.com/en-us/102654)
[Locate Apple Team ID](https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/)
