### ISSUE TITLE
[Bug]: New Install on MacOS Ventura 13.6

### ISSUE THREAD

**Issue by rgreenphoto** [NativePHP/laravel#216]
### What happened?

Would you like to install the NativePHP NPM dependencies? Yes
Installing NPM dependencies (This may take a while)...

 Installing NPM dependencies using the npm package manager...

 Fetching latest dependencies…

> NativePHP@1.0.0 postinstall
> node electron-builder install-app-deps

Binary Source:  /Users/rgreen/Code/nativephp/vendor/nativephp/php-bin/bin/
Binary Filename:  php
Arch:  arm64
Platform:  darwin
Copying PHP file(s) from /Users/rgreen/Code/nativephp/vendor/nativephp/php-bin/bin/mac/x86 to /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/php
Copied PHP binary to  /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/php
Copied certificate file to /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/cacert.pem

added 573 packages, and audited 574 packages in 3s

81 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

 ┌ Would you like to start the NativePHP development server ────┐
 │ No                                                           │
 └──────────────────────────────────────────────────────────────┘

  NativePHP scaffolding installed successfully.
php artisan native:serve
  Starting NativePHP dev server…

 Fetching latest dependencies…

 Installing NPM dependencies (This may take a while)...

 Installing NPM dependencies using the npm package manager...

 Fetching latest dependencies…

> NativePHP@1.0.0 postinstall
> node electron-builder install-app-deps

Binary Source:  /Users/rgreen/Code/nativephp/vendor/nativephp/php-bin/bin/
Binary Filename:  php
Arch:  arm64
Platform:  darwin
Copying PHP file(s) from /Users/rgreen/Code/nativephp/vendor/nativephp/php-bin/bin/mac/x86 to /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/php
Copied PHP binary to  /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/php
Copied certificate file to /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/cacert.pem

up to date, audited 574 packages in 627ms

81 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

 Starting NativePHP app

 Running the dev script with npm...

 Fetching latest dependencies…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.4.7 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 71ms.

build the electron main process successfully

-----

vite v4.4.7 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 6ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3130
    at /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:47:69
    at Generator.next (<anonymous>)
    at /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

API server started on port 4000

Starting PHP server... /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/resources/php/php artisan serve /Users/rgreen/Code/nativephp

Making sure app folders are available

(node:27038) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at callPhp (/Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:53:38)
    at /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:141:9
    at Generator.next (<anonymous>)
    at /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12)
    at /Users/rgreen/Code/nativephp/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:122:45
    at new Promise (<anonymous>)
(Use `Electron --trace-warnings ...` to show where the warning was created)

(node:27038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

### How to reproduce the bug

laravel new nativephp
No Starter Kit
PHPUnit 
No - Git Repo
SQLite DB
cd nativephp
php artisan native:install
php artisan native:serve

### Package Version

0.4.0

### PHP Version

8.2.11

### Laravel Version

10.10

### Node Version

18.18.0

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
@rgreenphoto Have you been able to make any advancement with this issue?

I've not personally come across this and there are some discussions online suggesting that it may be one/a combination of:
- a permissions issue
- an architecture issue (ARM vs Intel, 32-bit vs 64-bit)

NativePHP seems to have determined that you're on an ARM Mac (M1+). Is that correct?

**Comment by simonhamp** [comment]
Please update to v0.6 of nativephp/electron. I believe this will solve your issue.

If not, feel free to reopen this ticket.

**Comment by keizah7** [comment]
0.6.3 same problem

```cmd
git:(main) ✗ php artisan native:serve

  Starting NativePHP dev server… 

 Fetching latest dependencies…

 Installing NPM dependencies (This may take a while)...

 Installing NPM dependencies using the npm package manager...

 Fetching latest dependencies…


> NativePHP@1.0.0 postinstall
> node ./node_modules/electron-builder/cli.js install-app-deps

  • electron-builder  version=24.13.3
Arch:  arm64
Platform:  darwin
  • loaded configuration  file=/Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/electron-builder.js

up to date, audited 630 packages in 1s

96 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 Starting NativePHP app

 Running the dev script with npm...

 Fetching latest dependencies…


> NativePHP@1.0.0 dev
> cross-env node php.js && electron-vite dev --watch

Binary Source:  /Users/arturas/Sites/health-hub/vendor/nativephp/php-bin/bin/mac/x86/php-8.3.zip
Binary Filename:  php
PHP version: 8.3
Unzipping PHP binary from /Users/arturas/Sites/health-hub/vendor/nativephp/php-bin/bin/mac/x86/php-8.3.zip to /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/resources/php
Copied certificate file to /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/resources/cacert.pem
Copied PHP binary to  /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/resources/php/php
vite v4.5.3 building for development...

watching for file changes...

build started...
✓ 3 modules transformed.
out/main/index.js  0.62 kB
built in 28ms.

build the electron main process successfully

-----

vite v4.5.3 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 6ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3177
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:64:69
    at Generator.next (<anonymous>)
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at execFile (node:child_process:359:17)
    at node:child_process:252:21
    at node:electron/js2c/asar_bundle:2:3177
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:49:69
    at Generator.next (<anonymous>)
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
API server started on port 4002
Starting PHP server... /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/resources/php/php artisan serve /Users/arturas/Sites/health-hub {}
Making sure app folders are available
(node:34220) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at callPhp (/Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:78:38)
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:179:9
    at Generator.next (<anonymous>)
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:4:12)
    at /Users/arturas/Sites/health-hub/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/server/php.js:168:45
    at new Promise (<anonymous>)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:34220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)


```
