### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'setIcon')

### ISSUE THREAD

**Issue by septianinet** [NativePHP/laravel#22]
### What happened?

I getting this error when run my laravel app with nativephp

[7075:0721/100333.390724:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[7075:0721/100333.390847:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property

(node:7075) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at NativePHP.<anonymous> (/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:81:26)
    at Generator.next (<anonymous>)
    at /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:4:12)
    at /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js:78:36
(Use `electron --trace-warnings ...` to show where the warning was created)

(node:7075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

### How to reproduce the bug

When i run native:serve command it give me this error

### Package Version

0.1.0

### PHP Version

8.1

### Laravel Version

10.2

### Which operating systems does with happen with?

Linux

**Comment by elsayed85** [comment]
try to navigate to the code and disable the lines 
vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js
            // if (process.env.NODE_ENV === 'development') {
            //     app.dock.setIcon(state_1.default.icon);
            // }
            
            just for debug

**Comment by septianinet** [comment]
> try to navigate to the code and disable the lines vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js // if (process.env.NODE_ENV === 'development') { // app.dock.setIcon(state_1.default.icon); // }
> 
> ```
>         just for debug 
> ```

The error for setIcon is fixed and the app success to run until database migration, the first error still exist and get new issue the binary cant executed.


start electron app...

[10137:0721/101839.138587:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[10137:0721/101839.138652:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property

Error: Command failed: /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php artisan native:config
/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: cannot execute binary file

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 126,
  killed: false,
  signal: null,
  cmd: '/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php artisan native:config',
  stdout: '',
  stderr: '/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: cannot execute binary file\n'
}

API server started on port 4000

Starting PHP server... /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php artisan serve /home/septiandev/Development/my-laravel-boilerplate

Making sure app folders are available

Migrating database...

/home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: cannot execute binary file

**Comment by mattsches** [comment]
> Migrating database...
>
> /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: /home/septiandev/Development/my-laravel-boilerplate/vendor/nativephp/electron/resources/js/resources/php: cannot execute binary file`

This is probably because the PHP binary used here is the MacOS binary. NativePHP does not support Linux yet (I've even read that somewhere but cannot find the source anymore; it's not in the docs).

```bash
$ file vendor/nativephp/electron/resources/js/resources/php 
vendor/nativephp/electron/resources/js/resources/php: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Comment by tochiv** [comment]
Fixed, but got new issue

Error: Command failed: /home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php artisan native:config
/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 1: ����
                                                                                                      ��: not found
/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 2: Syntax error: word unexpected (expecting ")")

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php artisan native:config',
  stdout: '',
  stderr: '/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 1: ����\f\x01\x02\x16�\x07�: not found\n' +
    '/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 2: Syntax error: word unexpected (expecting ")")\n'
}

API server started on port 4000
Starting PHP server... /home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php artisan serve /home/tochiv/PhpstormProjects/testNative
Making sure app folders are available

Migrating database...

/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 1: ����
                                                                                                      ��: not found
/home/tochiv/PhpstormProjects/testNative/vendor/nativephp/electron/resources/js/resources/php: 2: Syntax error: word unexpected (expecting ")")


libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[14070:0721/121046.768100:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by antonioanerao** [comment]
I managed to use the project in Ubuntu

After you run php artisan native:install, say no when it ask you to run the server. Than, copy you php file from /usr/bin/php to nativephp/vendor/nativephp/php-bin/bin/mac/x86

**Comment by antonioanerao** [comment]
I managed to use the project in Ubuntu

After you run php artisan native:install, say no when it ask you to run the server. Than, copy you php file from /usr/bin/php to nativephp/vendor/nativephp/php-bin/bin/mac/x86.

After that when you run php artisan native:run it will use your php library instead of the mac php library version

**Comment by patoui** [comment]
@antonioanerao thank you for that information! I've added a few more details below.

Steps:
- `php artisan native:install` when prompted to start the development server select "no"
- run the commands below from the project root
```bash
sed -i 's/app.dock.setIcon(state_1.default.icon);/\/\/app.dock.setIcon(state_1.default.icon);/g' vendor/nativephp/electron/resources/js/node_modules/nativephp-electron/dist/index.js
cp -L /usr/bin/php vendor/nativephp/php-bin/bin/mac/x86/php
```
- run `php artisan native:serve`

Here's a gist with a script
https://gist.github.com/patoui/494689db112b11d52a63be34dc538511

**Comment by horaciod** [comment]
> 

works for linux mint 21 , thanks

**Comment by simonhamp** [comment]
You probably don't want to copy the executable built on your platform as it's most likely dynamically linked. **This will likely only work on your machine**

This means it won't be distributable to other machines when you come to package up your app for distribution.

You need a static build of PHP specifically for Linux.

First-party Linux support is coming very soon (we've already built the binaries, we just need to package them up)

**Comment by bpjuli22** [comment]
Bug fixed for demo for Linux OS:
first of all copy the php file from linux:
cp -L /usr/bin/php yourAppDirectory/vendor/nativephp/php-bin/bin/mac/x86/php

second comment the setIcon issue:
path: yourAppDirectory/vendor/nativephp/electron/resources/js/node_modules/@nativephp/electron-plugin/dist/index.js
comment: line 79 or find setIcon and comment it.

finally,
run: php artisan native:serve

**Comment by antonioanerao** [comment]
> You probably don't want to copy the executable built on your platform as it's most likely dynamically linked. **This will likely only work on your machine**
> 
> This means it won't be distributable to other machines when you come to package up your app for distribution.
> 
> You need a static build of PHP specifically for Linux.
> 
> First-party Linux support is coming very soon (we've already built the binaries, we just need to package them up)

That`s just a way to hack around while we wait for the linux support :D We want to play with NativePHP. I`m already making some nice stuff just for fun.

**Comment by mpociot** [comment]
The `setIcon` code now only gets executed on macOS
