### ISSUE TITLE
[Bug]: Unable to build on CI

### ISSUE THREAD

**Issue by eamirgh** [NativePHP/laravel#229]
### What happened?

Could not build on linux or windows platform on a fresh installation of laravel and nativephp.

### How to reproduce the bug

Here is the link to repo: [https://github.com/eamirgh/nativephp](https://github.com/eamirgh/nativephp)

### Package Version

0.4.0

### PHP Version

8.1|8.2

### Laravel Version

10.0.0

### Node Version

lts

**Comment by eugenefvdm** [comment]
This bug report contains very little information except:

> Here is the link to repo

Looking at the CI in the repo, the error that pops up is this:

```
TTY mode requires /dev/tty to be read/writable.

  at vendor/symfony/process/Process.php:1023
    1019▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1020▕         }
    10[21](https://github.com/eamirgh/nativephp/actions/runs/6919106809/job/18822072689#step:8:22)▕ 
    10[22](https://github.com/eamirgh/nativephp/actions/runs/6919106809/job/18822072689#step:8:23)▕         if ($tty && !self::isTtySupported()) {
  ➜ 10[23](https://github.com/eamirgh/nativephp/actions/runs/6919106809/job/18822072689#step:8:24)▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');
```

Is this the actual error you are referring to, namely about TTY mode issues?

**Comment by eamirgh** [comment]
In fact, the following error is for the Linux CI workflow, for Windows it hangs and never throws an error or exits, both github workflow files are included in repo the steps are pretty straight forward and clear.

**Comment by eugenefvdm** [comment]
My gut feeling is this being open source you should be doing some troubleshooting and reporting your findings instead of sending people off to another repo.

**Comment by simonhamp** [comment]
@eamirgh I can't see the logs any more as they have expired. Please can you provide all the necessary details in this ticket?

**Comment by simonhamp** [comment]
It's possible that some of the underlying issues here will already be solved.

Hard to say because I haven't seen those issues first-hand, but there have been significant improvements since v0.4.

Please upgrade to the latest version (0.6.1) and try again.
