### ISSUE TITLE
[Bug]: Php binary /vendor/nativephp/electron/resources/js/resources/php: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by elsayed85** [NativePHP/laravel#23]
### What happened?

Error: Command failed: /home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php artisan native:config
/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php: 1: Syntax error: "(" unexpected

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php artisan native:config',
  stdout: '',
  stderr: '/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php: 1: Syntax error: "(" unexpected\n'
}

API server started on port 4000

Starting PHP server... /home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php artisan serve /home/sayed/Desktop/DesktopApps/ray

Making sure app folders are available

Migrating database...

/home/sayed/Desktop/DesktopApps/ray/vendor/nativephp/electron/resources/js/resources/php: 1: Syntax error: "(" unexpected

### How to reproduce the bug

php artisan native:serve

### Package Version

0.10

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by akashpoudelnp** [comment]
I am facing same issue

**Comment by akashpoudelnp** [comment]
@antonioanerao is there any workaround for windows
=

**Comment by antonioanerao** [comment]
> # @antonioanerao is there any workaround for windows

Sorry I didnt tried it

**Comment by akhilmohan07** [comment]
> I managed to use the project in Ubuntu
> 
> After you run php artisan native:install, say no when it ask you to run the server. Then, copy you php file from /usr/bin/php to nativephp/vendor/nativephp/php-bin/bin/mac/x86.
> 
> After that when you run php artisan native:run it will use your php library instead of the mac php library version

its not working for me. i'm using linux, any other alternative solution

**Comment by marknuyens** [comment]
I'm using Ubuntu 22.04.02 but it's not working for me. Getting the same error when running `php artisan native:serve`.
After seeing the error there are a couple of other messages, but no app is launching neither showing on localhost:5137.

**Comment by gasner** [comment]
copy your php file from /vendor/nativephp/php-bin/bin/linux/x64 to /vendor/nativephp/php-bin/bin/mac/x86.

**Comment by KrzysztofPlaczek** [comment]
> copy your php file from `/vendor/nativephp/php-bin/bin/linux/x64` to `/vendor/nativephp/php-bin/bin/mac/x86`.

this works on ubuntu

**Comment by shakeel9115** [comment]
this is not working in zorin os 
`/vendor/nativephp/php-bin/bin/linux/x64 to /vendor/nativephp/php-bin/bin/mac/x86.
`
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev
> electron-vite dev --watch

vite v4.4.7 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 224ms.

build the electron main process successfully

-----

vite v4.4.7 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 41ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/nodesol/vendor/nativephp/electron/resources/js/node_modules/electron/dist/electron ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/nodesol/vendor/nativephp/electron/resources/js/node_modules/electron/dist/electron',
  path: '/home/nodesol/vendor/nativephp/electron/resources/js/node_modules/electron/dist/electron',
  spawnargs: [ '.' ]
}

Node.js v18.17.0


My system:
OS: Linux Zorin OS
PHP Version: 8.2.8

**Comment by mpociot** [comment]
Closing this as we don't have official Linux support yet.

**Comment by KrzysztofPlaczek** [comment]
> Closing this as we don't have official Linux support yet.

how come?
![image](https://github.com/NativePHP/laravel/assets/109726216/2059cec3-9fe2-4a55-a841-5eb5398b2a38)
https://nativephp.com/docs/1/getting-started/installation

**Comment by NPKIN1998** [comment]
> Closing this as we don't have official Linux support yet.

looking forward to have it as i will simplify this up fast

**Comment by Bbcar225** [comment]
> > copy your php file from `/vendor/nativephp/php-bin/bin/linux/x64` to `/vendor/nativephp/php-bin/bin/mac/x86`.
> 
> this works on ubuntu

Work for me

**Comment by bardh78** [comment]
> /vendor/nativephp/php-bin/bin/linux/x64

Yep. Thanks.

**Comment by ZELMAT** [comment]
J'ai un bug sur windows :

Error: spawn php ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs: [
    '-dxdebug.start_with_request=yes',
