### ISSUE TITLE
Changing Default Icon

### ISSUE THREAD

**Issue by sinarahmany** [NativePHP/laravel#235]
### Discussed in https://github.com/NativePHP/laravel/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **sinarahmany** December  3, 2023</sup>
Hi, I`m trying to change the default icon but no luck so far. Any suggestions would be greatly appreciated!
</div>

**Comment by MrBhola** [comment]
@sinarahmany  for menu bar  icon you can refer to https://nativephp.com/docs/1/the-basics/menu-bar#menu-bar-icon  . Thank

**Comment by Luis96920** [comment]
Excellent.
