### ISSUE TITLE
[Bug]: Driver [github] is not supported.

### ISSUE THREAD

**Issue by Gagi33** [NativePHP/laravel#236]
### What happened?

I have the message "Driver [github] is not supported. But in the documentation, github realease is possible.

### How to reproduce the bug

make a php:artisan native:publish

### Package Version

0.4.0

### PHP Version

8.3.0

### Laravel Version

10.35.0

### Node Version

18.17

**Comment by yasmoto1995** [comment]
Update the package version: Verify if there are any updates available for the package you're using. If a newer version is available, consider updating to see if the issue has been addressed in the latest release.

Check PHP and Laravel compatibility: Confirm that the PHP version (8.3.0) and Laravel version (10.35.0) you're using are compatible with the package. Sometimes, certain features or drivers may require specific versions to work correctly.

Good Luck.

**Comment by Gagi33** [comment]
Hello,

I have another error now : 

NativePHP updater provider [gitHub] is not defined.

Can you help me ? 

Thank you.

**Comment by yasmoto1995** [comment]
To solve this error, you can try the following steps:

Double-check the spelling and case sensitivity of the provider name ("gitHub" in this case). Make sure it matches the correct provider name defined in your configuration.

Verify that you have correctly set up the NativePHP updater provider for GitHub. Ensure that you have provided the necessary tokens, credentials, or URLs required for the provider to connect and fetch updates.

Review the documentation or support resources related to the software or application you are using. Look for specific instructions or examples on how to configure the NativePHP updater provider correctly.

Good luck.

**Comment by Gagi33** [comment]
Hello,

Thank you. 

I've managed to upload the source code for my application to Github. It's work fine.

However, I still have a question. I've put my application into production mode and it's signed by Apple, but I can't manage to update it automatically.

When I upload a new version to Github, the application doesn't update. 

Can you help me ?

Thank you very much.

**Comment by yasmoto1995** [comment]
git pull is impossible?

**Comment by yasmoto1995** [comment]
Ensure that you have set up the necessary automation or deployment pipeline for your application. Double-check if all the required steps, such as building, packaging, and deploying the new version, are correctly configured.

**Comment by Gagi33** [comment]
> git pull is impossible?

When the application is at the customer's, they don't have access to my git. So the application would have to update itself automatically as soon as I published a new version on github. That's how it's supposed to work, isn't it?

> Ensure that you have set up the necessary automation or deployment pipeline for your application. Double-check if all the required steps, such as building, packaging, and deploying the new version, are correctly configured.

This is the case. Everything is configured as requested in your documentation. Uploading the new version to git works. All that's missing is the client-side application update.

Thanks for your help.

**Comment by simonhamp** [comment]
@Gagi33 the Github config didn't get added until last month.

Please run `composer update` to get the latest version.
