### ISSUE TITLE
[Bug]: No such file or directory: 'run'

### ISSUE THREAD

**Issue by nouman-aceuss** [NativePHP/laravel#24]
### What happened?

I was expecting that the native php app window will launch. but i encountered this error
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'

### How to reproduce the bug

We can reproduce it using ubuntu 18.04. and then run following commands.

composer require nativephp/electron
php artisan native:install
php artisan native:serve

on serving the app you must see the error

### Package Version

0.1.0

### PHP Version

8.1.9

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

**Comment by dextromethorphanum** [comment]
same problem.

 Would you like to start the NativePHP development server (yes/no) [no]:
 > yes

Starting NativePHP dev server…
Fetching latest dependencies…
00h00m00s 0/0: : Starting NativePHP app…
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
NativePHP scaffolding installed successfully.

**Comment by felipealvesprestes** [comment]
Same problem here

Starting NativePHP dev server…
Fetching latest dependencies…
00h00m00s 0/0: : Starting NativePHP app…
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'

PHP
`
PHP 8.1.21 (cli) (built: Jul 10 2023 22:42:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
`

Laravel
`
Laravel Framework 10.15.0
`

**Comment by Ham3D** [comment]
same problem

**Comment by BataBoom** [comment]
🤞🤞

**Comment by MitotiMX** [comment]
Same problem
running PHP 8.1.21 on x64 Ubuntu 22
Fresh install Laravel install

**Comment by devsrv** [comment]
same problem

![image](https://github.com/NativePHP/laravel/assets/26733312/4e52ecf9-de1b-4968-829c-4989362a5977)

**Comment by sjess** [comment]
same

**Comment by sjess** [comment]
Do ```sudo npm install -g yarn```

**Comment by AdameLeNgolo** [comment]
Hi there i have the same problem. I use Linux Mint 
![Capture d’écran du 2023-07-24 13-48-21](https://github.com/NativePHP/laravel/assets/25395221/6e09a292-4905-426e-82d3-fa46280069df)

**Comment by devsrv** [comment]
if you don't mind a temporary salutation then follow this: https://gist.github.com/ShaneShipston/8bb7cabc423cf0cc64da0eacafa53171

worked for me

**Comment by AdameLeNgolo** [comment]
i think this is for Windows users but i'm on Linux Mint system

**Comment by mpociot** [comment]
This should be fixed now 👍
