### ISSUE TITLE
[Bug]: PHP8.2 support

### ISSUE THREAD

**Issue by CodeTechNL** [NativePHP/laravel#242]
### What happened?

When running `artisan native:serve` the application doesn't open. After reading the logs I got:

```
Error: Command failed: APP_DIR/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 255,
  killed: false,
  signal: null,
  cmd: 'APP_DIR/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '\n' +
    'Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.17. in APP_DIR/vendor/composer/platform_check.php on line 24\n',
  stderr: ''
}

```

APP_DIR is the path to my project which I removed for privacy. After downgrading to PHP 8.1, everything worked as expected

I couldnt find anything about PHP 8.2 support so if I missed something from the docs, im sorry

### How to reproduce the bug

Complete new installation

### Package Version

0.4.0

### PHP Version

8.2.0

### Laravel Version

10.39

### Node Version

18.17

### Which operating systems does with happen with?

macOS

### Notes

Apple M1

**Comment by yo-mike** [comment]
Hi @CodeTechNL, I found a work around if you use/have Laravel Herd:

`cp $HOME/Library/Application\ Support/Herd/bin/php82 ./vendor/nativephp/electron/resources/js/resources/php/php`

See this discussion thread: https://github.com/NativePHP/laravel/discussions/200

**Comment by CodeTechNL** [comment]
Sorry, missed the issue #200. I just downgraded my PHP, also works in my case. Thanks anyway @yo-mike

**Comment by abishekrsrikaanth** [comment]
@CodeTechNL does this cause any issues with production deployments on mac?

**Comment by CodeTechNL** [comment]
> @CodeTechNL does this cause any issues with production deployments on mac?

Can't say, my app isn't in production.  Also production isn't recommended according the docs

**Comment by abishekrsrikaanth** [comment]
OK, i actually meant creating a build and testing that? Not actually Production deployments
