### ISSUE TITLE
[Bug]:  php artisan native:install not working

### ISSUE THREAD

**Issue by Wilsonabdiel** [NativePHP/laravel#244]
### What happened?

When I try to install the package to a laravel app is gets stuck and doesn't work even after hours.
![Screenshot 2024-01-14 191934](https://github.com/NativePHP/laravel/assets/102998096/b275c7dd-cb2f-47e6-9164-20b619cb8e4f)

### How to reproduce the bug

Installation
`composer require nativephp/electron`
You can install it on an existing Laravel application, or [start a new one].
`php artisan native:install`

### Package Version

^0.4.0

### PHP Version

PHP 8.2.12

### Laravel Version

10.40.0

### Node Version

21.4.0

### Which operating systems does with happen with?

Windows

**Comment by OlinB** [comment]
I have the exact same issue, is there any known fix or workaround ?

**Comment by Wilsonabdiel** [comment]
> I have the exact same issue, is there any known fix or workaround ?

I'm yet to find a workaround, but when I do, I'll be sure to post it here

**Comment by alnutile** [comment]
For me I run that and then when I run the serve that it offers to run I get:

![CleanShot 2024-02-20 at 21 22 44@2x](https://github.com/NativePHP/laravel/assets/365385/a332b55b-46e5-4f7b-acb8-1f3c047171b8)

Even though I am running herd with a default php 8.2 

Then if I open this file `vendor/composer/platform_check.php` and remove:

```php
if (!(PHP_VERSION_ID >= 80200)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.2.0". You are running ' . PHP_VERSION . '.';
}
```

It will run and the window pops up BUT it still has an error in the background:

```bash
Error: Command failed: /Users/alfrednutile/Code/nativephp_llmassistant/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/alfrednutile/Code/nativephp_llmassistant/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '\n' +
    '   ERROR  Command "native:config" is not defined. Did you mean one of these?  \n' +
    '\n' +
    '  ⇂ native:build  \n' +
    '  ⇂ native:install  \n' +
    '  ⇂ native:migrate  \n' +
    '  ⇂ native:minify  \n' +
    '  ⇂ native:publish  \n' +
    '  ⇂ native:queue  \n' +
    '  ⇂ native:serve  \n' +
    '\n',
  stderr: ''
}
```
If this is not related to above I will make a new ticket.

**Comment by KajPe** [comment]
Seems it get stuck on the confirm function at vendor\nativephp\electron\src\Traits\Installer.php. I can get pass it by just pressing enter. Same again a further on.

**Comment by KajPe** [comment]
Further investigating, seems to be a problem in vendor\nativephp\electron\src\Commands\InstallCommand.php
If you change both callSilent() to simple call() then all the questions turns visible. Has something to do with process output set to null (to hide output) and failing to turn on again.

**Comment by avazquez-bit** [comment]
just hint enter a few seconds after the process begins, it worked for me.

**Comment by alnutile** [comment]
> just hit enter few seconds after the process begins, it worked for me.

not a great user experience :)

**Comment by simonhamp** [comment]
Confirmed! On a new install, running on Windows, it seems that using `callSilent` obscures the _next_ prompt for some reason.

This seems to be a bug specific to Windows. It could be how the shell handles moving between command contexts or it may be in Laravel or Symfony Console, I'm not sure yet.

I've pushed a fix which will be released shortly.
