### ISSUE TITLE
[Bug]: native build for win wont open

### ISSUE THREAD

**Issue by Iwan28TT** [NativePHP/laravel#245]
### What happened?

The native build is correct, but when running the setup/installer and attempting to open the application, it does not launch. The issue occurs after initiating the application, but there is no visible window.

![image](https://github.com/NativePHP/laravel/assets/117277096/22e6f188-a11d-47a7-b426-90408d853a00)
![image](https://github.com/NativePHP/laravel/assets/117277096/7bba43ba-6c26-42f3-b7fb-7d77b2b8328c)
![image](https://github.com/NativePHP/laravel/assets/117277096/22625ac9-2be1-4434-bba8-15a58d3aa854)

### How to reproduce the bug

php artisan native:build win -vvv

### Package Version

2.0.0

### PHP Version

8.2.4

### Laravel Version

10.40.0

### Node Version

18.17.1

**Comment by bishwajitcadhikary** [comment]
Same ☹. 
Have you got any solution?

**Comment by Iwan28TT** [comment]
Nope, I fixed it for mac  but I can't fix it for win

**Comment by Iwan28TT** [comment]
when you run the setup it should be installed.
if you try to start NativePHP in your command line you will get an error (at least I had). maybe you'll get a little further now

![Knipsel](https://github.com/NativePHP/laravel/assets/117277096/30576d28-237a-41d8-94af-89e078d6db69)

**Comment by thenexxuz** [comment]
Is there any update on this issue? I would LOVE to be able have a Windows build of my app.

**Comment by EPuigdemont** [comment]
Make sure that you are instantiating a Menu or Window in your NativeAppServiceProvider or elsewhere in your application to trigger opening an application window. 
Mac will do this without needing to be instructed, but on Windows without specifically instantiating a Window::open() method you won't get any.

First, I instantiate the a 'main' (main is the default window that is created if you don't specify a name for it) window in the NativeAppServiceProvider boot method:

```
class NativeAppServiceProvider implements ProvidesPhpIni
{
    public function boot(): void
    {
          Window::open('main)
                      ->width(800)
                      ->height(800);
     }
}
```

This should open a window when the application boots by itself.

If you also want to control opening this main window (or any other) elsewhere by an event, like clicking on a menubar element, or elsewhere in your application you can make an Event and trigger it, make sure that this event is not using the queue.

I created an event I called OpenMainWindow where I simply call an instance of the Window::open method, like this:
```
class OpenMainWindow
{
    use Dispatchable;

    public function __construct()
    {
        Window::open('main')
            ->minWidth(600)
            ->minHeight(300)
            ->width(1400)
            ->height(800)
            ->rememberState();
    }

 
    public function broadcastOn(): array
    {
        return [
            new PrivateChannel('channel-name'),
        ];
    }
}
```

And I dispatch this Event inside the MenuBar when clicking an element, which I defined in the boot method of NativeAppServiceProvider, like follows:

```
MenuBar::create()
            ->withContextMenu(
                Menu::new()
                    ->event(OpenMainWindow::class, 'Open Application Window')
                    ->quit()
            )
            ->width(1400)
            ->height(800)
            ->icon(public_path('menuBarIcon@2x.png'))
            ->showDockIcon();
```

**Comment by KajPe** [comment]
In the .env file (check the config\nativephp.php file for info) add:
NATIVEPHP_APP_ID=myapp.nativeapp.app
Should solve the index 0 error.

Also add:
NATIVEPHP_UPDATER_ENABLED=false

**Comment by simonhamp** [comment]
When you see these errors in the terminal at runtime, you can usually find something in the Laravel logs that indicates where the error lies.

**Comment by simonhamp** [comment]
Builds likely wouldn't have worked for Windows due to the way that the PHP executable was configured...

Up until today!

There is a new release which should solve this issue.

Please update to nativephp/electron v0.6
