### ISSUE TITLE
Symlink bug on app boot-up

### ISSUE THREAD

**Issue by arnor01** [NativePHP/laravel#250]
### What happened?

I have made a NativePHP app which works great. Inside the application I added logging of the errors to a private slack channel, to keep tracks of errors.
When testing the app I came accross the error `symlink(): Argument #1 ($target) must be of type string, array given`, but my application still worked so ignored it for some time.
But the errors keeps coming back so I looked into it a bit and found out it happens everytime the `storage:link` command is ran, if I'm correct that will be run on every startup of the application.

It lucky doesn't bother the working of the application, but still wanted to address this here in case I can do something about it or that it actually is a bug.

```
symlink(): Argument #1 ($target) must be of type string, array given
#0 /Applications/{appname}/Contents/Resources/app.asar.unpacked/resources/app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(355): symlink(Array, '/Applications/P...')
#1 /Applications/{appname}p/Contents/Resources/app.asar.unpacked/resources/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php(49): Illuminate\Filesystem\Filesystem->link(Array, '/Applications/P...')
#2 /Applications/{appname}/Contents/Resources/app.asar.unpacked/resources/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Foundation\Console\StorageLinkCommand->handle()
```

### How to reproduce the bug

Haven't had time too try it on a new project, but I think it happens on every build app. Or at least on Mac and Linux :)

### Package Version

0.4.0

### PHP Version

8.2

### Laravel Version

10.25

### Node Version

21.5

### Which operating systems does with happen with?

macOS, Linux

**Comment by EPuigdemont** [comment]
I have this issue as well.

I noticed that if I don't run the command `php artisan storage:link --force` I am seeing errors during the build command related to the storage folder not being found in the app/public/ directory.

After running the command and then building the application, the error is gone, and I haven't seen any other errors on my logs regarding this issue.

It seems like the default storage location is not set in the native app without running the command and so it looks for it in the wrong place.

**Comment by arnor01** [comment]
@EPuigdemont I will try that whenever I have to update the application!

**Comment by arnor01** [comment]
@EPuigdemont I have tried this today and it changed the error to: `symlink(): Read-only file system`. But that seems more like a device related problem than a NativePHP problem.

**Comment by simonhamp** [comment]
Interesting! I've not come across this. I'll look into it

**Comment by KirillDakhnyuk** [comment]
@simonhamp I experienced the same error yesterday. For me `php artisan storage:link --force` did not change the error.

**Comment by simonhamp** [comment]
@KirillDakhnyuk Are you on Mac or Linux?

**Comment by KirillDakhnyuk** [comment]
@simonhamp Mac M1.

**Comment by simonhamp** [comment]
@KirillDakhnyuk Is it blocking your app from running?

When and where do you see the error?

**Comment by KirillDakhnyuk** [comment]
@simonhamp actually it did not. I see the error inside `/Users/kirilldakhnyuk/Library/Application Support/clipstone/storage/logs/laravel.log` every time when I start the app.
Not sure if it help but I pushed the code https://github.com/KirillDakhnyuk/Clipstone

**Comment by bedus-creation** [comment]
Yeah I am also facing this issue

**Comment by simonhamp** [comment]
Please make sure you've updated to the latest versions. If this issue still persists after upgrading, feel free to re-open

**Comment by miagg** [comment]
same here on my first test build.
