### ISSUE TITLE
[Bug]: Fresh Install on Mac with Herd (and without Herd)

### ISSUE THREAD

**Issue by alnutile** [NativePHP/laravel#252]
### What happened?

I follow the docs and `php artisan native:install` should install and serve. But instead it errors out.

For me I run that and then when I run the serve that it offers to run I get:

![CleanShot 2024-02-20 at 21 22 44@2x](https://github.com/NativePHP/laravel/assets/365385/a332b55b-46e5-4f7b-acb8-1f3c047171b8)

Even though I am running herd with a default php 8.2 

Then if I open this file `vendor/composer/platform_check.php` and remove:

```php
if (!(PHP_VERSION_ID >= 80200)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.2.0". You are running ' . PHP_VERSION . '.';
}
```

It will run and the window pops up 

![CleanShot 2024-02-20 at 21 25 54@2x](https://github.com/NativePHP/laravel/assets/365385/af5647f2-2af4-4b62-b993-71b3195bbf63)

BUT it still has an error in the background:

```bash
Error: Command failed: /Users/alfrednutile/Code/nativephp_llmassistant/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/alfrednutile/Code/nativephp_llmassistant/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '\n' +
    '   ERROR  Command "native:config" is not defined. Did you mean one of these?  \n' +
    '\n' +
    '  ⇂ native:build  \n' +
    '  ⇂ native:install  \n' +
    '  ⇂ native:migrate  \n' +
    '  ⇂ native:minify  \n' +
    '  ⇂ native:publish  \n' +
    '  ⇂ native:queue  \n' +
    '  ⇂ native:serve  \n' +
    '\n',
  stderr: ''
}
```
If this is not related to above I will make a new ticket.

### How to reproduce the bug

Fresh mac install
Install Herd 
PHP8.2 is the default
laravel new some_folder
composer require nativephp/electron
php artisan native:install

See the error.

### Package Version

0.4.0

### PHP Version

8.2

### Laravel Version

10

### Node Version

20.11.0

### Which operating systems does with happen with?

macOS

**Comment by gwleuverink** [comment]
Hi @simonhamp. Your solution works in Laravel 10 but not in 11 since it requires a minimum PHP version of 8.2

https://laravel.com/docs/11.x/releases#php-8

Is there a workaround to spin up the server with Laravel 11?

**Comment by simonhamp** [comment]
I'm going to try and pick this up today

**Comment by roshanproductions** [comment]
How soon is it expected to support Laravel 11 and php 8.3? Thank you for your amazing work on this library.

**Comment by alnutile** [comment]
> How soon is it expected to support Laravel 11 and php 8.3? Thank you for your amazing work on this library.

I think the first step is rock solid stability before trying to keep up with the latest Laravel and PHP.
Though I look forward to that too it is a lot of work for one person.

**Comment by simonhamp** [comment]
New builds of PHP are coming this week. These will include both PHP 8.2 and 8.3, _and_ the version of PHP will align with your system's version of PHP (likely the one you used to install the Composer dependencies), so this error should be far less likely to appear!

Keep your eye on the releases of [`nativephp/electron`](/nativephp/electron/releases) over the next few days.

**Comment by simonhamp** [comment]
New releases are out. Please upgrade to nativephp/electron v0.6
