### ISSUE TITLE
[Bug]: Failed to install on Laravel 11

### ISSUE THREAD

**Issue by dbelyaeff** [NativePHP/laravel#256]
### What happened?

Failed to install NativePHP on Laravel 11.

``` 
Your requirements could not be resolved to an installable set of packages.

 Problem 1
    
nativephp/electron[0.1.0, ..., 0.4.0] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.3] but these were not loaded, likely because it conflicts with another require.
Root composer.json requires nativephp/electron * -> satisfiable by nativephp/electron[0.1.0, ..., 0.4.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require nativephp/electron:*" to figure out if any version is installable, or "composer require nativephp/electron:^2.1" if you know which you need.
```

### How to reproduce the bug

1. Fresh Laravel 11 installation
2. composer require nativephp/electron
3. php artisan native:install

### Package Version

0.4.0

### PHP Version

8.2.16

### Laravel Version

11

### Node Version

18.15

### Which operating systems does with happen with?

macOS

**Comment by emeryntumba** [comment]
Is there any update about this? I encounter the same problem on Windows

**Comment by dbelyaeff** [comment]
Is NativePHP alive? Any roadmap?

**Comment by meliani** [comment]
Hello you can check those PRs, i just fixed the issue :
https://github.com/NativePHP/laravel/pull/262
https://github.com/NativePHP/electron/pull/89

**Comment by kdrmlhcn** [comment]
@mpociot @simonhamp Could you please merge the Laravel 11 PR?

**Comment by simonhamp** [comment]
@meliani Those have been merged and released

**Comment by simonhamp** [comment]
There is a problem _building_ apps using Laravel 11, but closing this issue as it can now be _installed_ in Laravel 11
