### ISSUE TITLE
[Bug]: Version of electron-plugin is not up-to-date in Electron repository

### ISSUE THREAD

**Issue by basst85** [NativePHP/laravel#266]
### What happened?

It's still using version 0.2.0 instead of version 0.3.1 of the electron-plugin, so not all new features are available in the api. 

### How to reproduce the bug

- Install latest version of NativePHP in Laravel project.
- Check the version of electron-plugin in \vendor\nativephp\electron\resources\js\node_modules\@nativephp\electron-plugin\package.json

### Package Version

0.5.0

### PHP Version

8.2.0

### Laravel Version

11.0

### Node Version

20.9.0

### Which operating systems does with happen with?

Windows

**Comment by simonhamp** [comment]
This should be fixed in [`nativephp/electron@0.5.1`](https://github.com/NativePHP/electron/releases/tag/0.5.1).

Please run `composer update` and try again.
