### ISSUE TITLE
[Bug]: No electron app entry file found

### ISSUE THREAD

**Issue by Rueff19** [NativePHP/laravel#27]
### What happened?

When trying to run `php artisan native:serve` an error is given:

`error during start dev server and electron app:
Error: No electron app entry file found: /Users/[name]/Sites/laravel-example/vendor/nativephp/electron/resources/js/out/main/index.js
    at ensureElectronEntryFile (/Users/[name]/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:26:23)
    at Object.startElectron (/Users/[name]/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-3592fc5a.js:120:5)
    at createServer (/Users/[name]/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/chunks/lib-86ea98bb.js:74:21)
    at async CAC.<anonymous> (/Users/[name]/Sites/laravel-example/vendor/nativephp/electron/resources/js/node_modules/electron-vite/dist/cli.js:48:9)`

### How to reproduce the bug

Follow the documentation installation steps and then run `php artisan native:serve`

### Package Version

0.1.0

### PHP Version

8.2.0

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

### Notes

Additional info:
npm - v9.5.0
yarn - v1.22.19
node - v18.15.0

**Comment by bangbangda** [comment]
me too

**Comment by kendaniels** [comment]
Same here. Tried a few things but can't get passed this error.

**Comment by pentiminax** [comment]
Same here:

![Error](https://github.com/NativePHP/laravel/assets/4866668/d7de477e-64ef-42d7-b39c-c27c30652b81)

**Comment by crosa7** [comment]
Same here

**Comment by yeminlideveloper** [comment]
same here

**Comment by LukasFreyCZ** [comment]
Same issue :)

**Comment by rappasoft** [comment]
This is a temp fix that worked for me: https://github.com/NativePHP/electron/issues/10#issuecomment-1644651637

**Comment by Rueff19** [comment]
> 

Brilliant, that worked. At least until we get a definitive fix.

**Comment by berrugo** [comment]
> This is a temp fix that worked for me: [NativePHP/electron#10 (comment)](https://github.com/NativePHP/electron/issues/10#issuecomment-1644651637)

@thanks @rappasoft, got it working too

**Comment by arnedeb** [comment]
Did anyone manage to get this working under Laravel Sail? I followed the steps from https://github.com/NativePHP/electron/issues/10#issuecomment-1644651637 after getting the app entry file error and now I'm getting the following error instead:

```
root@a58a045c52af:/var/www/html# php artisan native:serve
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…
yarn run v1.22.19
warning package.json: No license field
$ electron-vite dev --watch
vite v4.3.9 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.54 kB
built in 95ms.

build the electron main process successfully

-----

vite v4.3.9 building for development...

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

/var/www/html/vendor/nativephp/electron/resources/js/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by CoeusCC** [comment]
Same issue. Will try @rappasoft's fix above

**Comment by rappasoft** [comment]
> Same issue. Will try @rappasoft's fix above

I installed a fresh instance yesterday and it compiled with no bugs, so they fixed it for me.

**Comment by bangbangda** [comment]
V0.1.1 fixed.
