### ISSUE TITLE
[Bug]: Problem with Intial Setup (pre-solved)

### ISSUE THREAD

**Issue by paulocardozo** [NativePHP/laravel#272]
### What happened?

php artisan native:install never finish to setup.

I changed all silent ->silentCall() to ->call() on Native\Electron\Commands\InstallCommand and had some progress, but it stucks on Fetching latest dependencies…

I'm trying to solve the problem myself, if I have some progress here, I update this card.

![image](https://github.com/NativePHP/laravel/assets/48040074/94ea273b-08ec-46ad-a23f-53ed5851e541)

### How to reproduce the bug

composer create-project laravel/laravel:^10 .

composer require nativephp/electron

php artisan native:install

### Package Version

0.5.0

### PHP Version

8.2.3

### Laravel Version

10

### Node Version

20.12.0

### Which operating systems does with happen with?

Windows

**Comment by paulocardozo** [comment]
->call() instead ->callSillent seems to be worked

**Comment by simonhamp** [comment]
If you choose 'no' to start the dev server during the `native:install` process, does the install process finish?

**Comment by simonhamp** [comment]
Found the cause of this and it's been fixed. Same as #244
