### ISSUE TITLE
Incomplete build on linux

### ISSUE THREAD

**Issue by avazquez-bit** [NativePHP/laravel#276]
### What happened?

The build of the app finish with an error even so, the app is builded and works fine, at least with the expected functionality
![screenshoot](https://github.com/NativePHP/laravel/assets/113546539/3d40017f-46b0-4cfa-89a3-d4fc5f5c3d6f)

### How to reproduce the bug

php artisan native:build linux

### Package Version

0.5.0

### PHP Version

8.2.10

### Laravel Version

10.10

### Node Version

18.20.2

### Which operating systems does with happen with?

Linux

**Comment by simonhamp** [comment]
It looks like this is an issue in the electron auto-updater with some specific concerns for Linux.

I notice it also mentioned "(beta)" somewhere in there.

I will investigate this at some point but as the app is building and working, I'm not too concerned right now.

I'm going to leave this open in the meantime.

**Comment by avazquez-bit** [comment]
yeah its the goal, finally, we can build the app, is just to keep in mind

**Comment by avazquez-bit** [comment]
Now the build app is correctly completed!!!
I'm gonna close this issue
