### ISSUE TITLE
[Bug]: App not opening after install

### ISSUE THREAD

**Issue by thegr8dev** [NativePHP/laravel#284]
### What happened?

During the installation process of version 0.6.1, a "Microsoft JS compilation error" occurred, which was resolved upon clicking "OK," allowing the build to proceed successfully. However, upon attempting to launch the application post-installation, it fails to open without presenting any error messages.

Windows 11 (23H2)  | Build : 22631.3447

### How to reproduce the bug

- Build Native PHP with win command.
- Install the build setup.
- Try to open the app and nothing will happen.

### Package Version

0.6.1

### PHP Version

8.1.2

### Laravel Version

10.10

### Node Version

18.17.0

### Which operating systems does with happen with?

Windows

**Comment by paulocardozo** [comment]
I'm facing this issue too.  @simonhamp do you know anything about that?

**Comment by paulocardozo** [comment]
Adding more information.  The process starts and can be viewed on Task Manager, but the application doesn't show any window.

![image](https://github.com/NativePHP/laravel/assets/48040074/5bcc8091-8d1c-41b3-95a2-dc9a11cdc254)

**Comment by simonhamp** [comment]
Rather than running the installer, if you go into the `dist/win-unpacked` folder and running the .exe located in there?

(Be sure to force quit those stray processes)

**Comment by paulocardozo** [comment]
> Rather than running the installer, if you go into the `dist/win-unpacked` folder, are you able to run the .exe located in there?
> 
> (Be sure to force quit those stray processes)

Yes. I've tried to run as admin too.  Process starts but nothing happens after.

**Comment by simonhamp** [comment]
@paulocardozo can you run `composer show nativephp/* --format=json` in the root of your app's development environment and past the output here please?

**Comment by paulocardozo** [comment]
> @paulocardozo can you run `composer show nativephp/* --format=json` in the root of your app's development environment and past the output here please?

Sure. Follows.

`{
    "installed": [
        {
            "name": "nativephp/electron",
            "direct-dependency": true,
            "homepage": "https://github.com/nativephp/electron",
            "source": "https://github.com/NativePHP/electron/tree/0.6.1",
            "version": "0.6.1",
            "description": "Electron wrapper for the NativePHP framework.",
            "abandoned": false
        },
        {
            "name": "nativephp/laravel",
            "direct-dependency": false,
            "homepage": "https://github.com/nativephp/laravel",
            "source": "https://github.com/NativePHP/laravel/tree/0.5.0",
            "version": "0.5.0",
            "description": "Laravel wrapper for the NativePHP framework.",
            "abandoned": false
        },
        {
            "name": "nativephp/php-bin",
            "direct-dependency": false,
            "homepage": "https://nativephp.com",
            "source": "https://github.com/NativePHP/php-bin/tree/0.4.0",
            "version": "0.4.0",
            "description": "PHP binaries used by the NativePHP framework",
            "abandoned": false
        }
    ]
}`

**Comment by paulocardozo** [comment]
I think I know what's going on.  I have multiple PHP versions installed, to run 8.1, I use php81 directive.  nativephp package is copying the base php version (8.0) to folder instead of 8.1 (version used for this Laravel 10 project).  I will try to replace default php to 8.1 and back with results.

**Comment by paulocardozo** [comment]
@simonhamp add me on LinkedIn if you can: https://www.linkedin.com/in/plneto.

I would like to talk directly with you and help to put this project ready to production.

**Comment by simonhamp** [comment]
NativePHP doesn't have PHP8.0... it starts at 8.1.

**Comment by simonhamp** [comment]
> add me on LinkedIn if you can

I'd love to help in this way, but I feel that kind of direct support requires paying for some consulting time.

Hope you understand

**Comment by thegr8dev** [comment]
PS :- This path should be corrected in docs, instead of this for dev build :-

C:\path\to\your\app\vendor\nativephp\resources\js\resources\php\php.exe -v

It should be :-

C:\path\to\your\app\vendor\nativephp\electron\resources\js\resources\php\php.exe -v

**Comment by paulocardozo** [comment]
@simonhamp well, my focus was on solve the issue, and help you to launch something that really works.  But, no problem, wait you solve these issues.  Cheers.

**Comment by simonhamp** [comment]
> Hi @simonhamp ,
> 
> 
> 
> As I checked in my system default php is 8.1.2 and I see binary that copied in build and without build 
> 
> 
> 
> version is also same. 
> 
> 
> 
> Without Build :-
> 
> 
> 
> ![image](https://github.com/NativePHP/laravel/assets/33778557/036a3cb1-b06a-4f02-b180-e0434f96c448)
> 
> 
> 
> With Build :- 
> 
> 
> 
> ![image](https://github.com/NativePHP/laravel/assets/33778557/1a91d754-0f1d-42c3-b88f-80d61062b042)
> 
> 
> 
> 
> 
> 

Were you able to execute those php.exe's in the CLI?

It looks from the screenshots you only executed your system PHP.

**Comment by thegr8dev** [comment]
Update I applied this :-

https://github.com/NativePHP/laravel/issues/277#issuecomment-2088805107

even after that i got error in build for fail build :-

Error copying app to resources
  • loaded configuration  file=C:\Users\Bacancy\Desktop\testapp\vendor\nativephp\electron\resources\js\electron-builder.js
Error: Command failed: php C:\Users\Bacancy\Desktop\testapp\vendor\nativephp\electron\resources\js\resources\php\php native:minify C:\Users\Bacancy\Desktop\testapp\vendor\nativephp\electron\resources\js\resources\app

but app is opening now, and executing as well. 

Now only above error is there which I'm looking what's going wrong.

**Comment by thegr8dev** [comment]
> > Hi @simonhamp ,
> > As I checked in my system default php is 8.1.2 and I see binary that copied in build and without build
> > version is also same.
> > Without Build :-
> > ![image](https://private-user-images.githubusercontent.com/33778557/327185953-036a3cb1-b06a-4f02-b180-e0434f96c448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODU3OTcsIm5iZiI6MTcxNDU4NTQ5NywicGF0aCI6Ii8zMzc3ODU1Ny8zMjcxODU5NTMtMDM2YTNjYjEtYjA2YS00ZjAyLWIxODAtZTA0MzRmOTZjNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE3NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZDcxMGNjYmM3ZDhlOGI1ZThkNzZlYjcyNTY5ZTBhNjkzMDI3YmFhMmU4YTZjNzE4YWFjYjcxZWE3Njc5MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kszvx58XEo7P7pi85IxdMZRiXCD5dC86N5d6XduCX1M)
> > With Build :-
> > ![image](https://private-user-images.githubusercontent.com/33778557/327186135-1a91d754-0f1d-42c3-b88f-80d61062b042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODU3OTcsIm5iZiI6MTcxNDU4NTQ5NywicGF0aCI6Ii8zMzc3ODU1Ny8zMjcxODYxMzUtMWE5MWQ3NTQtMGYxZC00MmMzLWI4OGYtODBkNjEwNjJiMDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE3NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMGIzOWQ0MjA2YTk0YjU0ZjZmODllOGI1ZjllYzgyMjViNzFiMWE2ZTNlMDgzZGRjNGNjMTBjNzc2N2QxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8uzjpsvNJlc9ybUsn4y8YCvdUsTwAzMwj19UMVG2sQ)
> 
> @thegr8dev Were you able to execute those php.exe's in the CLI?
> 
> It looks from the screenshots you only executed your system PHP.

Yep they are executing !

**Comment by paulocardozo** [comment]
@simonhamp I guess the problem is different versions of php (8.1.27/8.1.2/8.1.28).  I was using php 8.1.27 and your package was using php 8.1.28.  I've deleted the project and started a new/blank project to test.  Soon I will be back with results.

**Comment by simonhamp** [comment]
@thegr8dev 

>but app is opening now, and executing as well.

🎉 Will get those fixes in place in core soon

>Now only above error is there which I'm looking what's going wrong.

I think that's a minor issue. The app can run despite it

**Comment by simonhamp** [comment]
Good insight. I'll put a patch up soon that sets a sensible default

**Comment by JeremieMercier** [comment]
> > @thegr8dev
> > > but app is opening now, and executing as well.
> > 
> > 
> > 🎉 Will get those fixes in place in core soon
> > > Now only above error is there which I'm looking what's going wrong.
> > 
> > 
> > I think that's a minor issue. The app can run despite it
> 
> so here is what i did ignore the code comment above. I guess that was for solve that js compilcation error.
> 
> in .env file just add **NATIVEPHP_APP_ID="com.foo.app"** or any app id you want and rebuild the app.
> 
> Boom it will work !

It works for me too, thx !
