### ISSUE TITLE
[Bug]: Cannot Build on Windows

### ISSUE THREAD

**Issue by noweh** [NativePHP/laravel#286]
### What were you trying to do?

I'm trying to launch `php artisan native:serve -v`

**Error:** Infinite "Running scheduler..."

**Stacktrace :**

"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
dev server running for the electron renderer process at:

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose

start electron app...

API server started on port 4000
Starting PHP server... C:\wamp64\www\livewire-memory-game\project\vendor\nativephp\electron\resources\js\resources\php\php.exe artisan serve C:\wamp64\www\livewire-memory-game\project []
Making sure app folders are available
Skipping Database migration while in development.
You may migrate manually by running: php artisan native:migrate
PHP Server started on port:  8100
Skip checkForUpdates because application is not packed and dev update config is not forced
checkForUpdatesAndNotify called, downloadPromise is null
Running scheduler...
Running scheduler...
Running scheduler...
Running scheduler...
Running scheduler...

### What happened?

Infinite "Running scheduler..."

### How to reproduce the bug

launch `php artisan native:serve -v` on Windows

### Package Versions

"nativephp/electron" : "0.6.1"

### PHP Version

8.1

### Laravel Version

10.10

### Node Version

18.16

### Which operating systems have you seen this occur on?

Windows

### OS version

Win 11

**Comment by simonhamp** [comment]
This is intentional - the scheduler runs every minute. This is just debug output alerting you to the fact that it ran
