### ISSUE TITLE
[Bug]: Queue worker not working on Windows

### ISSUE THREAD

**Issue by Lexian-droid** [NativePHP/laravel#293]
### What were you trying to do?

I'm trying to run ``php artisan native:queue`` on Windows 11

### What happened?

It returns the following error:

```
php .\artisan native:queue

  Starting NativePHP queue worker… 

   Symfony\Component\Process\Exception\RuntimeException 

  TTY mode is not supported on Windows platform. 

  at vendor\symfony\process\Process.php:1013     
    1009▕      */
    1010▕     public function setTty(bool $tty): static
    1011▕     {
    1012▕         if ('\\' === \DIRECTORY_SEPARATOR && $tty) {
  ➜ 1013▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1014▕         }
    1015▕
    1016▕         if ($tty && !self::isTtySupported()) {
    1017▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');

  1   vendor\laravel\framework\src\Illuminate\Process\PendingProcess.php:321
      Symfony\Component\Process\Process::setTty()

  2   vendor\laravel\framework\src\Illuminate\Process\PendingProcess.php:249
      Illuminate\Process\PendingProcess::toSymfonyProcess("D:\Documents\Web Native Projects\Tos-Generator\vendor\nativephp\electron\src\Commands/../../resources/js/resources/php/php artisan queue:work")
```

### How to reproduce the bug

Perform these tasks on Windows
- Create new project
- In your project run ``php artisan native:queue``
- You'll see the error

### Package Versions

{     "installed": [         {             "name": "nativephp/electron",             "direct-dependency": true,             "homepage": "https://github.com/nativephp/electron",             "source": "https://github.com/NativePHP/electron/tree/0.6.2",             "version": "0.6.2",             "description": "Electron wrapper for the NativePHP framework.",             "abandoned": false         },         {             "name": "nativephp/laravel",             "direct-dependency": false,             "homepage": "https://github.com/nativephp/laravel",             "source": "https://github.com/NativePHP/laravel/tree/0.5.2",             "version": "0.5.2",             "description": "Laravel wrapper for the NativePHP framework.",             "abandoned": false         },         {             "name": "nativephp/php-bin",             "direct-dependency": false,             "homepage": "https://nativephp.com",             "source": "https://github.com/NativePHP/php-bin/tree/0.4.0",             "version": "0.4.0",             "description": "PHP binaries used by the NativePHP framework",             "abandoned": false         }     ] }

### PHP Version

8.3.6

### Laravel Version

PHP 8.3.6 (cli) (built: Apr 10 2024 14:53:44) (NTS Visual C++ 2019 x64) Copyright (c) The PHP Group Zend Engine v4.3.6, Copyright (c) Zend Technologies

### Node Version

v18.8.0

### Which operating systems have you seen this occur on?

Windows

### OS version

Windows 11 (23H2)

### Notes

Please note that I am specifically trying to run the queue worker, running ``php artisan native:serve`` works fine, but I'd like to be able to run the queue worker, so that I may run tasks in the background, if it's possible.

**Comment by simonhamp** [comment]
@Lexian-droid are you tyring to run the queue worker manually here? This should be running when your app boots.

Are you saying this error is coming out in the terminal when you're running `native:serve` at the point where it starts the queue worker?

**Comment by Lexian-droid** [comment]
> @Lexian-droid are you tyring to run the queue worker manually here? This should be running when your app boots.
> 
> Are you saying this error is coming out in the terminal when you're running `native:serve` at the point where it starts the queue worker?

Well, what I am doing is dispatching the job from my controller, and when the job is ran, it gets added to the queue successfully, but it doesn't leave the queue, which is why I think something is wrong, the queue worker may not be functioning properly? it's why I was trying to run it manually

**Comment by simonhamp** [comment]
You are probably right!

(I'd expect this same error to be logged elsewhere when your app is running, maybe `{appdata}/storage/logs/`?).

The Publish command [looks like this](https://github.com/NativePHP/electron/blob/main/src/Commands/PublishCommand.php#L41), but the queue worker command [looks like this](https://github.com/NativePHP/electron/blob/main/src/Commands/QueueWorkerCommand.php#L45)

Could you try updating `QueueWorkerCommand` to be more like `PublishCommand` in your environment to see if it's that?

**Comment by Lexian-droid** [comment]
> You are probably right!
> 
> (I'd expect this same error to be logged elsewhere when your app is running, maybe `{appdata}/storage/logs/`?).
> 
> The Publish command [looks like this](https://github.com/NativePHP/electron/blob/main/src/Commands/PublishCommand.php#L41), but the queue worker command [looks like this](https://github.com/NativePHP/electron/blob/main/src/Commands/QueueWorkerCommand.php#L45)
> 
> Could you try updating `QueueWorkerCommand` to be more like `PublishCommand` in your environment to see if it's that?

Sure I can give that a try, but I do want to mention, my application when you start it using native:serve, it does actually output an error into laravel.log

The error is ``local.ERROR: Database file at path`` it happens as soon as the app starts, maybe that could be something of interests as well? It's maybe important to note, this is a project I'm trying to convert to use NativePHP, kind of as a prototype.

**Comment by simonhamp** [comment]
Does that database file exist?

**Comment by Lexian-droid** [comment]
> Does that database file exist?

I've created it, it's being strange now though, it's basically using both databases at once, which seems a little improper, I've deleted database.sqlite because I thought it didn't need it, because it was basically using the regular database up until now where it does seem to need it, but it seems to only be that way for the queue, everything else seems normal. 

Is this normal behavior?

**Comment by Lexian-droid** [comment]
I think I solved the issue, I've checked around a little bit, and realized the "Awesome-nativephp" repo has some projects in it, some of these projects have this in common, their .env.example has:
```env
DB_CONNECTION=sqlite
DB_DATABASE=database/nativephp.sqlite
```
written inside, my .env only has ``DB_CONNECTION=sqlite`` and it's lacking the second line, I think this is my issue, unless this is not the issue? I won't close the issue yet, just in case. Either way, I hope we find progress on this! Thanks for your help by the way, I really appreciate it, and thanks for what you do. :)

**Comment by simonhamp** [comment]
I doubt that's related to this problem.

Did you try adding those para martes to the `->tty()` call in your version of the `QueueWorkerCommand`?

**Comment by Lexian-droid** [comment]
As for the automated queue worker, it has fixed my problem, however regarding the regular command, it's indeed still broken, I'll give this a shot now.

In our chat, the issue was that the queue worker in general wasn't working, in relation to the automated queue, it was because Laravel didn't think it had the right database, it couldn't move the failed jobs to a failed jobs table, but the dispatcher was adding it to the right table in the right database, so, telling laravel to use the right database, has lead to the right result. Therefore, it is now working in terms of that. (That's what I meant by adding something to the .env file)

But, yes sadly the manual one isn't working, and so I have added the ``->tty()`` as you requested, and I have the following result:

![Screenshot 2024-05-04 073212](https://github.com/NativePHP/laravel/assets/83799577/833e1cee-60d9-4061-86e5-553b31c1832b)
Here is the changes, I replaced the ``->tty()`` with ``->tty(PHP_OS_FAMILY != 'Windows' && ! $this->option('no-interaction'))``

![image](https://github.com/NativePHP/laravel/assets/83799577/a5fc44b9-8470-4213-8341-1f8f4b1806b2)
The command now displays the error "``'D:\Documents\Web' is not recognized as an internal or external command,
operable program or batch file.``" but my path has spaces in it, it's ``D:\Documents\Web Native Projects\Tos-Generator``

So, I did removed the spaces, and it resulted in this:
Sidenote: Is it possible to fix that? the "Spaces in path" I'm pretty sure it is, you just put double quotes surrounding the path.

![image](https://github.com/NativePHP/laravel/assets/83799577/6a8fa1df-5b7f-4847-8584-f3f5754797a6)
The queue worker does run, but after a bit of time, it does seem to close with an error, as seen in the screenshot, but maybe that's simply because the app itself isn't running?

**Comment by simonhamp** [comment]
>As for the automated queue worker, it has fixed my problem

Which solution are you referring to, the `.env` missing `DB_DATABASE`?

**Comment by simonhamp** [comment]
Ok interesting that you found that issue with `.env` missing the DB. It suggests we're not passing the right environment variables into the queue worker from Electron.

As for running the queue worker manually, it looks like your job is trying to call something within NativePHP which requires communicating with Electron.

So if your app isn't running when you manually run the queue worker, it won't work and you'll get errors like this.
