### ISSUE TITLE
Websockets package doesn't support Laravel 11

### ISSUE THREAD

**Issue by gwleuverink** [NativePHP/laravel#295]
### What were you trying to do?

Hi @simonhamp, thanks for this awesome project 🚀 

There is one thing I came across while implementing event broadcasting with Laravel 11.

It seems that [Laravel Websockets](https://github.com/beyondcode/laravel-websockets) package NativePHP integrates with has been archived and doesn't work with Laravel 11. 

I need to dispatch events from a scheduled command. As I understand it right now, this doesn't work with electron's IPC. It seems only native-php events are emitted this way (or am I perhaps missing something?)

It seems like in order to support event broadcasting the same way in Laravel 11 support for Reverb needs to be added.

### What happened?

The Laravel websockets package can't be installed with Laravel 11. 

### How to reproduce the bug

1. Create a new Laravel 11 project
2. Install NativePHP (0.6.3)
3. Try to install Laravel websockets -> `composer require beyondcode/laravel-websockets`

### Package Versions

0.6.3

### PHP Version

8.2.16

### Laravel Version

11.6.0

### Node Version

21.7.3

### Which operating systems have you seen this occur on?

macOS

### OS version

macos 14.4.1

**Comment by gwleuverink** [comment]
I've been doing some digging and it seems Laravel events are not handled using IPC in the same way native-events are. 

In my case I'm dispatching a event from the scheduler using the log broadcasting connection. This event is logged in the browser (from `preload.js`) and I'd like to listen to it in a Livewire component. 

From `preload.js` I gather native events are passed through Livewire, but regular events are just logged. I believe such behaviour could be achievable by adding a extra check [here](https://github.com/NativePHP/electron-plugin/blob/65581c8b1cef851f0eed65d575694e566012b1ef/src/preload/index.ts#L12) to detect if it is a Laravel event, then hand it off to Livewire.

Would you consider a PR adding this?

**Comment by simonhamp** [comment]
@gwleuverink all PRs are welcome 😊 

The section you link to is specific to `log` events, which are generated by the [`LogWatcher`](https://github.com/NativePHP/laravel/blob/main/src/Logging/LogWatcher.php).

All other events generated by Electron [that we explicitly](https://github.com/NativePHP/electron-plugin/blob/65581c8b1cef851f0eed65d575694e566012b1ef/src/index.ts#L45-L65) handle should be [transformed into a `native-event`](https://github.com/NativePHP/electron-plugin/blob/65581c8b1cef851f0eed65d575694e566012b1ef/src/server/utils.ts#L29-L33) for the front-end and should be [handled by Livewire already](https://github.com/NativePHP/electron-plugin/blob/65581c8b1cef851f0eed65d575694e566012b1ef/src/preload/index.ts#L18-L60).

(These are also sent to the Laravel back-end, which allows you to listen to those events wherever makes the most sense for your application)

Since Laravel Reverb is out and Laravel Websockets has been archived, we may look to support Reverb.

But you should be able to achieve what you need _without_ a websocket server _in most cases_. If you're struggling with your specific implementation, try reaching out on [Discord](https://discord.gg/fyVAjPqA).

**Comment by gwleuverink** [comment]
Awesome! thanks for the detailed explanation. I've been able to achieve what I set out to do. It was actually pretty straightforward.

For other folks trying to do the same: In order to listen to events dispatched with the log driver and pass it to Livewire you can do the following:

Add `ipcRenderer` to the js bundle (I added it to the window for the example)

``` js
window.ipcRenderer = require('electron').ipcRenderer // somehow has issues using import
```

Then in your component you can do something like this

``` blade
<script>
    document.addEventListener('livewire:navigated', () => {
        ipcRenderer.on('log', (event, { level, message, context }) => {

            // Listen to MessageReceived event (could check against regex too)
            if (message.startsWith('Broadcasting [App\\Events\\MessageReceived] on channels [nativephp]')) {
   
                // Either dispatch event to be handled by Livewire (following native-events convention)
                window.Livewire.dispatch('native:App\\Events\\MessageReceived')
                
                // Or invoke the Livewire method directly
                @wire.someMethod()
            }
        })
    })
</script>
```

I was thinking a case can be made to handle regular Laravel events just like native-events, so this extra wiring can be skipped. But this is so little code that it is pretty manageable as is. Thanks for the assist and info @simonhamp

**Comment by gwleuverink** [comment]
Hi @simonhamp, I've got a follow up question regarding workaround I posted before. 

It follows the same thread as the question above, but please let me know if I should ask this somewhere else. 🙏🏻 

So, as demonstrated above, I'm listening to a `log` event that's fired when a Laravel event is dispatched on the `nativephp` channel, then triggering a method on a Livewire component. 

This workaround works great in development, but after building the app, no `log` events are dispatched on ipc.

After some digging I've found that both the [LogWatcher](https://github.com/NativePHP/laravel/blob/047c774013fe3c1fad9b9b04870bb570973467c2/src/NativeServiceProvider.php#L60) and the [electron server log route](https://github.com/NativePHP/electron-plugin/blob/4d105bd1ead3094450a98ced7de5a223998ff34f/src/server/api.ts#L56) are not registered when the app env isn't development.

This is probably for good reason, but I can't help but feel I'm missing something. What's the recommended way to listen to Laravel events without using websockets? Like you said, it seems most of these type of challenges can be tackled without a websocket server.

Hope you can provide some clarity! I'd be happy to contribute this back to the docs once I've got it all figured out

**Comment by simonhamp** [comment]
> What's the recommended way to listen to Laravel events without using websockets? Like you said, it seems most of these type of challenges can be tackled without a websocket server.

I agree that we could achieve quite a lot of this without websockets.

> This workaround works great in development, but after building the app, no log events are dispatched on ipc.

The log watcher is explicitly only for debugging and you shouldn't really abuse it in this way.

So it would be a case of building a similar solution to the `LogWatcher` that can pass messages across to the frontend, but that we don't disable in production.

As in your code, it would also need a listener on the frontend using `ipcRenderer.on()`, so this would need to be covered in the docs.

Feels like a nice easy PR...

**Comment by gwleuverink** [comment]
Thanks Simon, I was breaking my head on this one. Thought I was missing something. 

It sure sounds like a great first contribution. I'll try my hand at it this week if no one beats me to it 👍

**Comment by gwleuverink** [comment]
@simonhamp I've pushed 2 PR's. Please let me know if I need to make any changes!

[NativePHP/laravel#367](https://github.com/NativePHP/laravel/pull/367)
[NativePHP/electron-plugin#37](https://github.com/NativePHP/electron-plugin/pull/37)

**Comment by Invsqa** [comment]
Check This

https://medium.com/@amolakh10/websocket-laravel-11-reverb-secure-https-private-on-local-machine-example-of-one-to-one-chat-ffede3a26900
