### ISSUE TITLE
Windows moving and relocated

### ISSUE THREAD

**Issue by avazquez-bit** [NativePHP/laravel#321]
### What were you trying to do?

When application is attached to some OS edge or corner and hit some button or link the windows, moves to the center or previous locations sometimes it becomes crazy and locates out of the screen or something else, the behavior is variable, I've check code, but there is no code to change this. and only happens on Windows OS when the applications is attaches, fullscreen and other conditions like, personalized size and position, work pretty well

I've tried to change some window parameters on NativeProviders, but nothing works.

This only happens in Windows OS, on linux works preatty well and MAC, I havent tried yet

Left video reference
https://share.vidyard.com/watch/A4VUekzQTxGmBcxJG9fdD7?

If video is not working, let me kwno, it was processing at the moment of extracing link

### What happened?

Windowd not to be moved

### How to reproduce the bug

In windows, and attaching application to some edge or corner and navigating

### Package Versions

0.6.3

### PHP Version

8.2

### Laravel Version

11.10

### Node Version

18.20.2

### Which operating systems have you seen this occur on?

Windows

### OS version

Win 11 Pro (23H2)

**Comment by simonhamp** [comment]
If i'm understanding correctly from your video, the window seems to jump when you click on a certain link in your UI? Is that correct?

**Comment by avazquez-bit** [comment]
Yes, thats it!!!

**Comment by simonhamp** [comment]
That sounds like a bug somewhere between Electron and Windows and is probably not to do with NativePHP

I found [this](https://github.com/electron/electron/issues/25359#issuecomment-1377820980) which seems partly related. There are other [similar](https://github.com/mattermost/desktop/pull/2730)-[sounding](https://github.com/responsively-org/responsively-app/issues/999) issues referencing that whole thread - the second one even has a video exhibiting the same behaviour!

So I'm going to close this issue as I don't think it's anything we can solve here within NativePHP

**Comment by avazquez-bit** [comment]
Excelent, thanks!!!
