### ISSUE TITLE
Class "ZipArchive" not found

### ISSUE THREAD

**Issue by ScArThaS1** [NativePHP/laravel#331]
### What were you trying to do?

In my development I use the Laravel Excel library to read a file and save it in the database but when I try to read the file I get the error Class "ZipArchive" not found and when I do some documentation it is because in the PHP version it is not that liberia is enabled

### What happened?

I try to read the file I get the error Class "ZipArchive" not found

### How to reproduce the bug

When I send the file to a Laravel path and try to read it, I get the error

### Package Versions

0.6.3

### PHP Version

8.3.6

### Laravel Version

11.10.0

### Node Version

18.14.2

### Which operating systems have you seen this occur on?

macOS

### OS version

macos13.5.1 (22G90)

**Comment by Rudeisnice** [comment]
Solutions is simple, NativePHP's bundled PHP binaries don't include the zip library, so you have to build php yourself.
See the [NativePHP PHP Binary Repo](https://github.com/NativePHP/php-bin) to build it yourself with the zip extension and replace the existing PHP binary

**Comment by artembabak** [comment]
> Solution is simple, NativePHP's bundled PHP binaries don't include the zip library, so you have to build php yourself. See the [NativePHP PHP Binary Repo](https://github.com/NativePHP/php-bin) to build it yourself with the zip extension and replace the existing PHP binary

@Rudeisnice How do I "replace the existing PHP binary"?

**Comment by kisuka** [comment]
> > Solution is simple, NativePHP's bundled PHP binaries don't include the zip library, so you have to build php yourself. See the [NativePHP PHP Binary Repo](https://github.com/NativePHP/php-bin) to build it yourself with the zip extension and replace the existing PHP binary
> 
> @Rudeisnice How do I "replace the existing PHP binary"?


1. Fork https://github.com/NativePHP/php-bin
2. Click on Actions.
3. Select the operating system build on the left side.
4. Click run workflow on right side.
5. Input your settings needed for the build of php.
6. Once action is finished, click on it to be presented with the binaries.
7. Follow what this PR does to give yourself to ability to specify the binaries location during compiling: https://github.com/NativePHP/electron/pull/101
