### ISSUE TITLE
Unable to set the minimum window size

### ISSUE THREAD

**Issue by Supernova3339** [NativePHP/laravel#334]
### What were you trying to do?

Set the minimum window size in a menubar app

### What happened?

The minimum window size is set and I am unable to freely modify the size beyond the minimum set

### How to reproduce the bug

Use the following in MenuBar::create

```php
->width(389)
->height(400)
->minWidth(389)
->minHeight(400)
```

### Package Versions

0.6.3 nativephp/electron, 0.5.2 nativephp/laravel, 0.4.0 nativephp/php-bin

### PHP Version

8.2.20

### Laravel Version

11.15.0

### Node Version

21.7.3

### Which operating systems have you seen this occur on?

Windows

### OS version

win 11 (23H2) (OS Build 22631.3737)

**Comment by omitobi** [comment]
Maybe you need to add these?

```php
 ->resizable(true)
 ->maximizable(true)
 ->minimizable(true);
```

**Comment by Supernova3339** [comment]
hey @omitobi, these flags you provided ( I saw via E-mail ), do not exist for MenuBar.

**Comment by simonhamp** [comment]
If your window's `minHeight` and `minWidth` match its `height` and `width`, isn't it just that you don't want the window to be resizable?

Have you tried [stopping it from being resizable](https://nativephp.com/docs/1/the-basics/windows#resizable-windows)?

**Comment by simonhamp** [comment]
Closing due to no response
