### ISSUE TITLE
IPC as documented doesn't work

### ISSUE THREAD

**Issue by MichelJonkman** [NativePHP/laravel#351]
### What were you trying to do?

Trying to listen to built in and custom events

### What happened?

The example in the docs doesn't work

### How to reproduce the bug

Copy the example from the docs

### Package Versions

Electron 0.7.0, Laravel 0.5.4, Bin 0.4.0

### PHP Version

8.3.10

### Laravel Version

11.21.0

### Node Version

18.18.1

### Which operating systems have you seen this occur on?

Windows

### OS version

Windows 10

### Notes

Links to the relevant docs:
https://nativephp.com/docs/1/digging-deeper/broadcasting#browser-events
https://nativephp.com/docs/1/digging-deeper/broadcasting#javascript

**Comment by gwleuverink** [comment]
Fixed by https://github.com/NativePHP/laravel/pull/367 @simonhamp?

**Comment by MichelJonkman** [comment]
@gwleuverink It looks like it does yeah, maybe a good idea to update the docs as well? The current code on there is incomplete and broken, I can't be the only one confused by it!

**Comment by gwleuverink** [comment]
Yep that PR is pending release next week 🎉 
You can preview the docs here https://github.com/NativePHP/nativephp.com/pull/44

**Comment by MichelJonkman** [comment]
> Yep that PR is pending release next week 🎉 You can preview the docs here [NativePHP/nativephp.com#44](https://github.com/NativePHP/nativephp.com/pull/44)

Aaah thank you! Glad to see this getting solved, I just about gave up on NativePHP due to radio silence here and on Discord 😬 

I'll close the issue since it's safe to say that it's fixed

**Comment by simonhamp** [comment]
@MichelJonkman sorry for missing your messages on Discord 😞 

Has been a busy period for me. I'll try to do better.

Thanks to more sponsorships lately I'll have more time for monitoring and replying to tickets and Discord.

Getting there steadily
