### ISSUE TITLE
php-sdk error In static-php-cli build 

### ISSUE THREAD

**Issue by mohamed-rnd** [NativePHP/laravel#356]
### What were you trying to do?

Hi
Thanks for the great package

I am trying to build a new php binary with intl extension
I ran this build command `bin/spc build --build-cli  "intl,bcmath,curl,json,mbstring,tokenizer,xml,zip"`

### What happened?

After starting the command above it fails while executing this command `C:\spc-build\static-php-cli\php-sdk-binary-tools\phpsdk-vs17-x64.bat -t nmake_cli_wrapper.bat --task-args php.exe`

### How to reproduce the bug

Install static-php-cli then download the needed packages then try to build with the given command above

### Package Versions

"nativephp/electron": "^0.7.0", "nativephp/php-bin": "^0.4.0", "nativephp/laravel": "0.5.4"

### PHP Version

8.2.18

### Laravel Version

^11.9

### Node Version

20.12.2

### Which operating systems have you seen this occur on?

Windows

### OS version

win 10

### Notes
I installed Visual Studio 2022

**Comment by syntafin** [comment]
Please share the still missing error message

**Comment by simonhamp** [comment]
@mohamed-rnd the errors you're referring to are related to the `static-php-cli` package and aren't related to NativePHP.

You should [raise issues](https://github.com/crazywhalecc/static-php-cli/issues/new) about this with the maintainer of that package
