### ISSUE TITLE
Laravel + Filament

### ISSUE THREAD

**Issue by bobimicroweber** [NativePHP/laravel#359]
### What were you trying to do?

I try to run laravel + filament admin panel 

### What happened?

But in browser error console shows:
file: http://127.0.0.1:8102/js/filament/support/support.js?v=3.2.110.0
support.js?v=3.2.110.0:1 Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at J (support.js?v=3.2.110.0:1:2141) 

### How to reproduce the bug

You can try to install laravel filament admin panel and bug will be reproduced 

### Package Versions

0.7.1

### PHP Version

8.20

### Laravel Version

11

### Node Version

20

### Which operating systems have you seen this occur on?

macOS

### OS version

latest version

<img width="999" alt="Screenshot 2024-09-04 at 15 03 37" src="https://github.com/user-attachments/assets/b0bccdcf-1e83-4552-83f7-e0af0a8a9c32">

**Comment by simonhamp** [comment]
Could it be [this](https://github.com/orgs/NativePHP/discussions/345)?

**Comment by bobicloudvision** [comment]
I try to run it with 
`LECTRON_RUN_AS_NODE=0 php artisan native:serve`
but nothing is changed..

I will try to found the solution and open pull request....

**Comment by simonhamp** [comment]
I'm going to close this as it's really an issue with Filament or one of their upstream dependencies. It looks like it's [already been raised with the Filament team](https://github.com/filamentphp/filament/discussions/12388). Please keep your investigation going, I'm sure you'll get to a fix one way or another
