### ISSUE TITLE
500 error on build only

### ISSUE THREAD

**Issue by Mohamed5550** [NativePHP/laravel#363]
### What were you trying to do?

I was trying to build the app for production after it worked fine on `native:serve`

### What happened?

I got error 500 after installing the exe file

### How to reproduce the bug

I am not sure, It was working fine, but now it always return 500 whatever I do

### Package Versions

"nativephp/electron": "^0.7.0", "nativephp/php-bin": "^0.4.0", "nativephp/laravel": "0.5.5"

### PHP Version

8.2.18

### Laravel Version

11.9

### Node Version

v20.17.0

### Which operating systems have you seen this occur on?

Windows

### OS version

Win 11

### Notes

If there is a way to show the cause of the 500 error on production it will be helpful

**Comment by Mohamed5550** [comment]
When I went to installatino folder and entered `win-unpacked\resources\app.asar.unpacked\resources\app` then typed `php artisan config:cache` it works fine

But everythime I build it gives 500 error
I still can't send the installer anywhere

**Comment by 00bx** [comment]
hello, i fixed the issue with the following steps.  

1. Uninstall the application:
    - Open the Control Panel (Win + R, type "control", press Enter)
    - Go to "Programs and Features" or "Apps & features"
    - Find "ur app name" in the list
    - Right-click and select "Uninstall" or click "Uninstall"
    - Follow the uninstallation prompts
2. Delete application data:
    - Press Win + R
    - Type "%localappdata%" and press Enter
    - Look for a folder named "ur app name" or something similar
    - Delete this folder
3. Delete roaming data:
    - Press Win + R
    - Type "%appdata%" and press Enter
    - Look for a "ur app name" folder and delete it if found
4. Clear temporary files:
    - Press Win + R
    - Type "%temp%" and press Enter
    - Delete any folders or files related to "ur app name" , im sure this will fix as it fixed mine, or u can disable the native update for future build u might not need to do those steps. NATIVEPHP_UPDATER_ENABLED=false in ur .env
