### ISSUE TITLE
The "intl" PHP extension is required to use the [format] method

### ISSUE THREAD

**Issue by antonarizal** [NativePHP/laravel#366]
### What were you trying to do?

I try to run laravel + filament admin panel

I create new filament-resource with filament

### What happened?

Internal Server Error

RuntimeException
The "intl" PHP extension is required to use the [format] method.

### How to reproduce the bug

When i submit button Create, i see **Internal Server Error**

### Package Versions

0.7.1

### PHP Version

8.2

### Laravel Version

11

### Node Version

20

### Which operating systems have you seen this occur on?

Windows

### OS version

win11

### Notes

![Screenshot 2024-09-09 100756](https://github.com/user-attachments/assets/4eb1b0cb-0906-460d-8ae2-f6bde348d68d)

**Comment by simonhamp** [comment]
This is being [tracked as a feature request](https://github.com/orgs/NativePHP/discussions/292), not a bug. `intl` extension isn't loaded, so this is expected behaviour, not a bug
