### ISSUE TITLE
[Bug]: Website Update Documentation 

### ISSUE THREAD

**Issue by Infamoustrey** [NativePHP/laravel#37]
### What happened?

Not sure if this is the right place to report this but the Updating your app page is missing https://nativephp.com/docs/1/digging-deeper/updater 

![image](https://github.com/NativePHP/laravel/assets/5813665/3561fa64-01e8-48a2-a55a-21633a71553b)

### How to reproduce the bug

Just visit the link

### Package Version

current

### PHP Version

8.2

### Laravel Version

9

**Comment by raulillana** [comment]
Just `$ composer update` and you're good to go.

**Comment by Infamoustrey** [comment]
Lol @raulillana just composer update their website?

**Comment by raulillana** [comment]
@Infamoustrey to update the app. LOL

**Comment by Infamoustrey** [comment]
@raulillana I see, I assumed this was documentation to update a deployed application not updating the dependencies. In either case the docs probably still need to be updated.

**Comment by Infamoustrey** [comment]
This was done
