### ISSUE TITLE
Outdated electron-plugin after composer update

### ISSUE THREAD

**Issue by gwleuverink** [NativePHP/laravel#372]
### What were you trying to do?

When a update is available and `composer update` ran, the underlying `electron-plugin` library isn't updated.

There is a chance people will ship builds with incompatible electron-plugin versions.

### What happened?

-

### How to reproduce the bug

When a update is available for `electron-plugin` and your `nativephp/electron` version supports it, I expect the `electron-plugin` to be updated when running composer update from my project

### Package Versions

0.5.7

### PHP Version

8.3

### Laravel Version

11

### Node Version

22

### Which operating systems have you seen this occur on?

macOS

### OS version

14.6

### Notes

Mentioned in Discord here along with a couple approaches for a fix:

https://discord.com/channels/1136045642154790955/1285535476891123844/1285907694343028787

**Comment by gwleuverink** [comment]
RFC #348 addresses this issue

**Comment by simonhamp** [comment]
Fixed via https://github.com/NativePHP/electron/pull/109
