### ISSUE TITLE
Database Seed Data Not Included In Build

### ISSUE THREAD

**Issue by hfzm** [NativePHP/laravel#384]
### What were you trying to do?

Thank you for this great technology. I was trying to build my application with sqlite3 database and I was trying to seed some data in development mode.

### What happened?

It shows the data without any errors in my application in development phase but when I build and package my application the seeded data is not included in the built mode. 

### How to reproduce the bug

Please solve this issue because we need some seeded data always either its development or production mode for example roles and permissions table data. Thanks in advance. Keep up the great work. 

### Package Versions

I am using the latest verson always.

### PHP Version

8.1

### Laravel Version

11

### Node Version

18

### Which operating systems have you seen this occur on?

Linux

### OS version

Ubuntu 24 LTS

**Comment by hfzm** [comment]
Yeah, so how can I do it? As you're saying I should build it in a way that
it should seed on each fresh installation, and as the installation process
is related to Electron and NativePHP configuration so I could not find
anything in the documentation to run my seeder files on fresh install. Your
help would be really appreciated in this if you can add some guidance to
the documentation it would be really helpful. Thanks in advance. It is
really a great technology and because of this, I am just one step away from
creating my project and presenting it to the public.

**Comment by simonhamp** [comment]
You can call the `db:seed` Artisan command from PHP using the `Artisan` facade.

Wrap that call in an `if` which checks your DB first to see if it has been seeded. (You might want an explicit record in one of your seeders that gives you a clear signal that seeding has happened)

Put that whole block somewhere that will run every time your app boots - e.g. the NativeServiceProvider - so that it runs every time.

**Comment by hfzm** [comment]
Thank you very much for your support, I really appreciate it. NativePHP is
a great project and I wish more success for it in the future and I hope it
will conquer the world of mobile applications too. Thanks again for your
email. I think it will do the job done and finally I can publish my desktop
application successfully.
