### ISSUE TITLE
[Bug]:  404 for requesting features or asking questions

### ISSUE THREAD

**Issue by inmanturbo** [NativePHP/laravel#39]
### What happened?

When attempting to ask a question or propose a feature one will encounter a 404 error, as there doesn't seem to be discussions enabled on the repository. 

https://docs.github.com/en/discussions/quickstart

### How to reproduce the bug

browse to issues, then click on anything other than "bug"

### Package Version

n/a

### PHP Version

n/a

### Laravel Version

n/a

### Which operating systems does with happen with?

Linux

**Comment by simonhamp** [comment]
Discussions are now enabled
