### ISSUE TITLE
Child process not starting and returning an error

### ISSUE THREAD

**Issue by SRWieZ** [NativePHP/laravel#401]
### What were you trying to do?

Start a child process

### What happened?

It seems that the request to electron to start the process returns null.

https://flareapp.io/share/qm1bXQ2P

### How to reproduce the bug

```php
ChildProcess::artisan(
    cmd: 'app:directories-watcher',
    alias: 'git',
    persistent: true
);
```

### Package Versions

0.6.1

### PHP Version

8.3.13

### Laravel Version

10.48.22

### Node Version

21.7.3

### Which operating systems have you seen this occur on?

macOS

### OS version

15.1

### Notes

@simonhamp, you have access to my repository. It may be easier for reproducing the bug.

**Comment by simonhamp** [comment]
I managed to get everything running... maybe I need to see the state of things on your machine to see what's up?

<img width="1045" alt="Screenshot 2024-11-07 at 23 23 44" src="https://github.com/user-attachments/assets/569c24d1-829f-478f-ab5e-50aa8fd6bbec">

**Comment by SRWieZ** [comment]
Oh, that's a bummer.

Thank you for trying.  I will come back when I know more.

From my understanding, the request to start the job returns null.

Is there any place I can look, like a Node.js error log?  
Also, I'm on an Intel Mac; is that something that could be related to the bug?

P.S. I had already tried removing the node_modules directory and vendor (just listened to your podcast ^^).

**Comment by simonhamp** [comment]
I've put a bit of work already into surfacing runtime errors in the terminal, which should help when you're using `native:serve` - but you won't get this unless you're on the latest version

**Comment by SRWieZ** [comment]
That was it.

I am ashamed; I did verify that I was on the latest version of every package before posting the issue with  
`composer show "nativephp/*" --format=json`

Fixed by upgrading to 8.*  
`composer require nativephp/electron -W`

**Comment by simonhamp** [comment]
No shame in it! This will be easier once we're past v1
