### ISSUE TITLE
Remove the `native:queue` command

### ISSUE THREAD

**Issue by simonhamp** [NativePHP/laravel#407]
See https://github.com/NativePHP/laravel/pull/402#issuecomment-2471008473

**Comment by JustinLawrenceMS** [comment]
Any possibility of bringing me on for this?

**Comment by simonhamp** [comment]
@JustinLawrenceMS what do you mean "bringing you on"? Are you offering to pick this issue up?

**Comment by JustinLawrenceMS** [comment]
> @JustinLawrenceMS what do you mean "bringing you on"? Are you offering to pick this issue up?

Yes, I didn't want to presume to fork it and put in a pull report if somebody was already going to work on it.
