### ISSUE TITLE
MenuBar app show a dock icon if you launch it twice (+video)

### ISSUE THREAD

**Issue by SRWieZ** [NativePHP/laravel#425]
### What were you trying to do?

Launching twice the same app should reopen the Navbar.

### What happened?

It showed a non-interactive dock icon.

### How to reproduce the bug

1. Build your app (a menubar app, important detail)
2. Install it
3. Launch it
4. Without closing it, try to relaunch it
5. You now have the icon in the dock, without really any window attached to it. I tried "File => Close window (CMD+W)" but it didn't work.

### Package Versions

electron: 0.8.7, laravel: 0.6.4, php-bin: 0.5.5

### PHP Version

8.3.13

### Laravel Version

11

### Node Version

v21.7.3

### Which operating systems have you seen this occur on?

macOS

### OS version

15.1 (24B83)

### Notes

Video of the issue:

https://youtu.be/zxrDvwVK9Os

Nothing fancy in the app:
```php
public function boot(): void
{
    MenuBar::create()
        ->label('searching...')
        ->withContextMenu(
            Menu::new()
                ->label('ISP Shower')
                ->separator()
                ->event(AskForRefresh::class, 'Refresh')
                ->separator()
                ->quit()
        )
        ->onlyShowContextMenu();

    event(new AskForRefresh);
}
```

**Comment by simonhamp** [comment]
Did this get resolved with recent updates to both Dock and MenuBar logic?

**Comment by SRWieZ** [comment]
Yes it's fixed!
