### ISSUE TITLE
FIlament "user" menu stuck open when using NativePHP

### ISSUE THREAD

**Issue by x7ryan** [NativePHP/laravel#435]
### What were you trying to do?

I have installed Filament onto my native PHP Laravel app,

### What happened?

Once I register my account and login, I the "user" menu in the upper right is stuck open and misaligned to where it is cut off, but only when accessing the app with native:serve. Since it works as intended when accessing though the browser it appears to specifically be an issue with nativePHP and/or electron.

![Screenshot 2024-11-25 150331](https://github.com/user-attachments/assets/428e424c-206a-4fac-8df1-5a55489c8139)

### How to reproduce the bug

Reproduction repo: https://github.com/x7ryan/native-filament

Run `php artisan native:serve`

Run `php artisan native:migrate`

Click though to register an account. Once logged in the user menu will be pre-expanded and will not close.

Then access the app though the browser, register and login the user menu functions as normal. 

### Package Versions

{     "installed": [         {             "name": "nativephp/electron",             "direct-dependency": true,             "homepage": "https://github.com/nativephp/electron",             "source": "https://github.com/NativePHP/electron/tree/0.8.7",             "version": "0.8.7",             "description": "Electron wrapper for the NativePHP framework.",             "abandoned": false         },         {             "name": "nativephp/laravel",             "direct-dependency": false,             "homepage": "https://github.com/nativephp/laravel",             "source": "https://github.com/NativePHP/laravel/tree/0.6.4",             "version": "0.6.4",             "description": "Laravel wrapper for the NativePHP framework.",             "abandoned": false         },         {             "name": "nativephp/php-bin",             "direct-dependency": false,             "homepage": "https://nativephp.com",             "source": "https://github.com/NativePHP/php-bin/tree/0.5.5",             "version": "0.5.5",             "description": "PHP binaries used by the NativePHP framework",             "abandoned": false         }     ] }

### PHP Version

8.3.13

### Laravel Version

11.33.2

### Node Version

22.3.0

### Which operating systems have you seen this occur on?

Windows

### OS version

Windows 11 Pro 23H2, Build #22631.4460

### Notes

Filament version: 3.2.124

**Comment by x7ryan** [comment]
It deems to be related specifically to Alpine within NativePHP/Electron

Some relevant JS console output:

```
livewire.js?id=38dc8241:1120 Alpine Expression Error: $refs.panel.toggle is not a function

Expression: "toggle"

 
livewire.js?id=38dc8241:1124 Uncaught 
TypeError: $refs.panel.toggle is not a function
    at Proxy.toggle (eval at safeAsyncFunction (livewire.js?id=38dc8241:1171:21), <anonymous>:5:25)
    at runIfTypeOfFunction (livewire.js?id=38dc8241:1207:26)
    at livewire.js?id=38dc8241:1195:11
    at tryCatch (livewire.js?id=38dc8241:1113:14)
    at livewire.js?id=38dc8241:3871:7
    at handler4 (livewire.js?id=38dc8241:3173:27)
    at livewire.js?id=38dc8241:3237:9
    at HTMLDivElement.<anonymous> (livewire.js?id=38dc8241:3175:54)
livewire.js?id=38dc8241:1120 Alpine Expression Error: $refs.panel.toggle is not a function

Expression: "toggle"

 
livewire.js?id=38dc8241:1124 Uncaught 
TypeError: $refs.panel.toggle is not a function
    at Proxy.toggle (eval at safeAsyncFunction (livewire.js?id=38dc8241:1171:21), <anonymous>:5:25)
    at runIfTypeOfFunction (livewire.js?id=38dc8241:1207:26)
    at livewire.js?id=38dc8241:1195:11
    at tryCatch (livewire.js?id=38dc8241:1113:14)
    at livewire.js?id=38dc8241:3871:7
    at handler4 (livewire.js?id=38dc8241:3173:27)
    at livewire.js?id=38dc8241:3237:9
    at HTMLDivElement.<anonymous> (livewire.js?id=38dc8241:3175:54)
livewire.js?id=38dc8241:1120 Alpine Expression Error: $refs.panel.toggle is not a function

Expression: "toggle"

 
livewire.js?id=38dc8241:1124 Uncaught 
TypeError: $refs.panel.toggle is not a function
    at Proxy.toggle (eval at safeAsyncFunction (livewire.js?id=38dc8241:1171:21), <anonymous>:5:25)
    at runIfTypeOfFunction (livewire.js?id=38dc8241:1207:26)
    at livewire.js?id=38dc8241:1195:11
    at tryCatch (livewire.js?id=38dc8241:1113:14)
    at livewire.js?id=38dc8241:3871:7
    at handler4 (livewire.js?id=38dc8241:3173:27)
    at livewire.js?id=38dc8241:3237:9
    at HTMLDivElement.<anonymous> (livewire.js?id=38dc8241:3175:54)
```

**Comment by simonhamp** [comment]
Seems [you're not the only one](https://github.com/orgs/NativePHP/discussions/330#discussioncomment-10767632) @x7ryan 

I think the answer you seek is [here](https://github.com/filamentphp/filament/discussions/12388#discussioncomment-10662099).

Please let me know if this solves your issue.
