### ISSUE TITLE
[Bug]: Database file at path [database/database.sqlite] does not exist. Ensure this is an absolute path to the database.

### ISSUE THREAD

**Issue by rawezhcode** [NativePHP/laravel#47]
### What happened?

custom  sqlite database is not working and not found

DB_CONNECTION=sqlite
DB_DATABASE=database/database.sqlite
DATABASE_URL=/database/database.sqlite
DB_FOREIGN_KEYS=false
NATIVEPHP_DATABASE_PATH=/database/database.sqlite

### How to reproduce the bug

Run `artisan nativephp:serve`

### Package Version

0.1.0

### PHP Version

8.2.0

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by olssonm** [comment]
The error is thrown from Laravel, not this package.

The error says exactly what the error is. You need to supply an absolute path, not a relative one which you have in your example. An absolute would be for instance `/Users/user/code/app/database/databse.sqlite`.

**Comment by rawezhcode** [comment]
> The error is thrown from Laravel, not this package.
> 
> The error says exactly what the error is. You need to supply an absolute path, not a relative one which you have in your example. An absolute would be for instance `/Users/user/code/app/database/databse.sqlite`. 


The problem is that the file location is not a problem and complete, when I run this command php artisan serve works very smoothly and no problems, but when I run this command php native:serve shows the error that I mentioned.

**Comment by olssonm** [comment]
That's odd, I think that it occurs with `php native:serve` because it also runs your migrations. With `php artisan migrate` the same error should occur if you're still using a relative path.

Have you tried using an absolute path?

**Comment by rawezhcode** [comment]
I solved the problem by replacing those parts.
I changed this in this file
`/vendor/nativephp/laravel/src/NativeServiceProvider.php`
![image](https://github.com/NativePHP/laravel/assets/53620168/c55aa9cb-12dc-4533-b756-f2dc085d4e04)

And  

Add this code to the `config/database.php` file

![image](https://github.com/NativePHP/laravel/assets/53620168/6e19b7a2-87c3-477a-92f5-7080a6502926)

After Adding this code to the `.env` file

```
DB_CONNECTION=sqlite
DB_DATABASE_NATIVEPHP="database/nativephp.sqlite"
```

**Comment by mpociot** [comment]
The database path gets automatically configured in the electron JavaScript helper. See https://github.com/NativePHP/electron-plugin/blob/main/src/server/php.ts#L26-L27
You should not manually modify this environment variable/setting.

**Comment by bdj-Razik** [comment]
I solved this problem with replacing 
env(...) to database_path(env(..))

<img width="520" alt="Image" src="https://github.com/user-attachments/assets/fd8b56d1-b3f9-4c3b-aa86-c8ea3a221e85" />
