### ISSUE TITLE
[Feature]: print with native is printer 

### ISSUE THREAD

**Issue by Hackbard** [NativePHP/laravel#57]
### What happened?

Hi

it would be great to choose from the system printers that are installed and print directly to it.

Expect an app where the orders will be printed out automatically.

Best regards 

### How to reproduce the bug

Print 500 orders with browser print function

### Package Version

1.0.0

### PHP Version

8.2.0

### Laravel Version

9.0.0

### Node Version

18.xx

### Which operating systems does with happen with?

Windows

### Notes

Should be available on all systems

**Comment by mpociot** [comment]
This was added 👍
