### ISSUE TITLE
[Bug]: artisan native:serve not updating/hot updating, throwing an error

### ISSUE THREAD

**Issue by PriceNathan** [NativePHP/laravel#64]
### What happened?

When I run the serve command, it hangs up on an error. it serves the app, but an outdated version of the app not reflecting the changes I've made, and it doesn't hot-reload with any changes.
My output when running php artisan native:serve (bold sections are my censorship):

Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…
yarn run v1.22.19
warning package.json: No license field
warning ../../../../../../../package.json: No license field
$ electron-vite dev --watch
vite v4.3.9 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 87ms.

build the electron main process successfully

-----

vite v4.3.9 building for development...

watching for file changes...

build started...
transforming (1) src/preload/index.js"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 14ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

API server started on port 4000

Starting PHP server... [**LOCAL SITE]**/vendor/nativephp/electron/resources/js/resources/php artisan serve /Users/nathanprice/PhpstormProjects/**[PROJECT NAME]**

Making sure app folders are available

Migrating database...

PHP Server started on port:  8100

(node:2216) electron: NSVisualEffectMaterialAppearanceBased has been deprecated and removed as of macOS 10.15.
(Use `Electron --trace-warnings ...` to show where the warning was created)

Skip checkForUpdates because application is not packed and dev update config is not forced
checkForUpdatesAndNotify called, downloadPromise is null

### How to reproduce the bug

I've encountered this bug across multiple projects when trying to install and serve nativePHP

### Package Version

0.1.1

### PHP Version

8.2

### Laravel Version

10

### Node Version

18.16.1

### Which operating systems does with happen with?

macOS

**Comment by PriceNathan** [comment]
> I'm getting the same errors. Here's one extra line I have in the error message:
> 
> `[18319:0724/132705.581041:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)`
> 
> Similar environment to OP:
> 
> Node v18.15.0 Mac OS Ventura 13.4.1 (Intel Mac, if that makes a difference) Laravel 10 PHP 8.2
> 
> Is there any way to just manually refresh the electron window after making code changes? I honestly wouldn't mind too much, I could still work on things despite any Hot Module Updates not working.

You know what, I'm seeing that same message as well! Agreed that manual refresh would be nice, something would be better than nothing. I'm currently using valet to serve in a browser for dev, but that's less than ideal considering the desired format & output.

**Comment by PriceNathan** [comment]
I know this is pre-release, but I'm hoping I can at least get the functionality you presented us with at Laracon to work for me locally. The experience so far has been buggy and challenging. This had been working for me for about an hour, and I started encountering this issue without any clear reason for it.

**Comment by PriceNathan** [comment]
> I'm getting the same errors. Here's one extra line I have in the error message:
> 
> `[18319:0724/132705.581041:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)`
> 
> Similar environment to OP:
> 
> Node v18.15.0 Mac OS Ventura 13.4.1 (Intel Mac, if that makes a difference) Laravel 10 PHP 8.2
> 
> Is there any way to just manually refresh the electron window after making code changes? I honestly wouldn't mind too much, I could still work on things despite any Hot Module Updates not working.

I got this same error after running `composer dump-autoload` and attempting to serve again, in addition to the output I specified above

**Comment by PriceNathan** [comment]
Tried creating a fresh Laravel app and installing, same issues

**Comment by drehimself** [comment]
@PriceNathan Check out this thread of the same issue: https://github.com/NativePHP/laravel/issues/63

I managed to get Hot Module Reloading working by adding `@vite('resources/js/app.js')` in `welcome.blade.php` (or your layout). Also, make sure vite is running via `yarn dev` or `npm run dev`.

**Comment by PriceNathan** [comment]
> @PriceNathan Check out this thread of the same issue: #63
> 
> I managed to get Hot Module Reloading working by adding `@vite('resources/js/app.js')` in `welcome.blade.php` (or your layout). Also, make sure vite is running via `yarn dev` or `npm run dev`.

Saw this, tried it, no success. Still has the same error, still does not compile and update my view.

**Comment by nathanjansen** [comment]
What helped me:
- I stopped the native server than `npm run build` 
- And than again `php artisan native:serve`
Now the problem should be gone.

**Comment by simonhamp** [comment]
I'll add something to the docs to cover hot reloading of your front-end code.
