### ISSUE TITLE
[Bug]: Request a feature issue is broken

### ISSUE THREAD

**Issue by richardanderson001** [NativePHP/laravel#65]
### What happened?

I clicked on issues->request a feature and got a broken link

### How to reproduce the bug

This is an issue in GitHub.  Click issues, then request a feature, finally see the broken page link.

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

9.0.0

### Node Version

18.17

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

This is an issue in GitHub.  Click issues, then request a feature, finally see the broken page link.

**Comment by simonhamp** [comment]
This has been fixed
