### ISSUE TITLE
[Bug]: Storage filesystems don't have configured drivers

### ISSUE THREAD

**Issue by Maxoplata** [NativePHP/laravel#70]
### What happened?

When I try to use any of the different filesystems defined [here](https://nativephp.com/docs/1/digging-deeper/files), I get the error (`user.home` filesystem in this example):

> Disk [user.home] does not have a configured driver.

### How to reproduce the bug

```
use Illuminate\Support\Facades\Storage;

...

$fileExists = Storage::disk('user.home')->exists('blah.txt');
```

### Package Version

0.1.1

### PHP Version

8.1.21

### Laravel Version

10.10.0

### Node Version

18.13.0

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
Sorry! Yeh I had intended to add them. I'll pick this up.

**Comment by mdloop** [comment]
I was having some serious doubts as to my knowledge of how this is supposed to work, since I could find zero references to those disks. Glad to see you're on it. Let me know if I can help.

**Comment by mpociot** [comment]
I added those disks in #99
