### ISSUE TITLE
[Bug]: ContextMenu  is not working

### ISSUE THREAD

**Issue by rawezhcode** [NativePHP/laravel#73]
### What happened?

```
 ContextMenu::register(
            Menu::new()
                ->event(MyEvent::class, 'Reload', 'CmdOrCtrl+R')
        );
```
ContextMenu  is not working to Reload pages 

### How to reproduce the bug

.

### Package Version

0.2.0

### PHP Version

8.2.0

### Laravel Version

10.10

### Node Version

19.6.1

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
As this was on version 0.2 of NativePHP, could you try upgrading to the latest version and seeing if that changes things?
