### ISSUE TITLE
[Bug]: In PendingProcess.php line 258: The process "npm update" exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by khalmurad** [NativePHP/laravel#79]
### What happened?

The 60 seconds set for building the application is too short. The first build takes at least 5-6 minutes. The reason is that it downloads and installs some packages related to the operating system to the computer. The next build may take less time, but it will take more than 60 seconds.

First building error:
<img width="1354" alt="image" src="https://github.com/NativePHP/laravel/assets/46134234/2472c767-b2a8-4e2f-9224-f87b0e61951b">

Next building error:
<img width="750" alt="image" src="https://github.com/NativePHP/laravel/assets/46134234/60bc8b9e-f054-4da5-bc93-11a2409f2782">

I fixed first and next errors like that:
I changed `timeout` attribute value in `Illuminate\Process\PendingProcess` class to `3600` second (by default was `60` second).

### How to reproduce the bug

Run the command php artisan native:build

### Package Version

latest

### PHP Version

8.2.8

### Laravel Version

10.16.1

### Node Version

20.5.0

### Which operating systems does with happen with?

macOS

**Comment by mpociot** [comment]
This is now fixed. I also removed the "npm update" call entirely from the build command.

**Comment by khalmurad** [comment]
> This is now fixed. I also removed the "npm update" call entirely from the build command.

Hi.
I downloaded the latest version via the composer update command. But the error could not be resolved.

**composer.json file:**
![Screenshot 2023-07-31 at 8 55 56 PM](https://github.com/NativePHP/laravel/assets/46134234/c046cf94-a0ea-45da-b550-daf0a060d5a7)

**composer.lock file:**
![Screenshot 2023-07-31 at 8 39 59 PM](https://github.com/NativePHP/laravel/assets/46134234/6a70b999-198e-4e0a-a4ab-4d41d224391c)

**Error message:**
![Screenshot 2023-07-31 at 8 57 23 PM](https://github.com/NativePHP/laravel/assets/46134234/7c85ad4c-b6b6-4b9e-bac1-67d32de5963d)
