### ISSUE TITLE
[Bug]: TTY mode is not supported on Windows platform.

### ISSUE THREAD

**Issue by ahmedtofaha10** [NativePHP/laravel#8]
### What happened?

when i start by 
native:serve i got this error
TTY mode is not supported on Windows platform.

### How to reproduce the bug

i using a windows 11 
i dont know if it's count

### Package Version

0.1.0

### PHP Version

8.2

### Laravel Version

10

**Comment by arif98741** [comment]
Got same issue 
![Screenshot_153](https://github.com/NativePHP/laravel/assets/17213478/fe65234f-288d-4ccd-bfca-c78763a32691)

**Comment by SneherAdor** [comment]
It seems that NativePHP is not currently supported on the Windows platform.

**Comment by londonarchipelago** [comment]
bc only builds "mac ready" software, don't know if they have one "complete" working saas, always ship quickly (with bugs) and on to the next... maybe focus on one thing at a time and execute properly?

**Comment by JulitoM3** [comment]
> Got same issue **Platform** `Windows 10` `PHP 8.2` `Laravel 10.15`
> 
> ![Screenshot_153](https://user-images.githubusercontent.com/17213478/254995961-fe65234f-288d-4ccd-bfca-c78763a32691.png)

as @mpociot said NativePHP is currently only for macOS

**Comment by arif98741** [comment]
> > Got same issue **Platform** `Windows 10` `PHP 8.2` `Laravel 10.15`
> > ![Screenshot_153](https://user-images.githubusercontent.com/17213478/254995961-fe65234f-288d-4ccd-bfca-c78763a32691.png)
> 
> as @mpociot said NativePHP is currently only for macOS

Still need to wait for updates

**Comment by TungPham296** [comment]
I had the same error as above and I realized that it seems that all errors are caused by using laragon. Probably should try by running directly on windows without running through laragon.

**Comment by ZekyTheWolf** [comment]
Would be nice to have it mentioned in docs... :)

**Comment by TungPham296** [comment]
@ZekyTheWolf Try running on windows without going through laragon and let me know the result(Image). I have a lot of work to do so I can't try it yet.

**Comment by ZekyTheWolf** [comment]
> @ZekyTheWolf Try running on windows without going through laragon and let me know the result(Image). I have a lot of work to do so I can't try it yet.

Done it, same result... Looks like its not currently for windows...

**Comment by thatal** [comment]
Me also getting the same error. So I went to symphony Process.php and manually set tty to false. Next it was showing Starting NativePHP app… but app never running or opening up.

![image](https://github.com/NativePHP/laravel/assets/17490342/7e0175a4-3b47-4357-a11e-2389da65e7c3)

**Comment by jumawilliam** [comment]
Same challenge here
![Capture](https://github.com/NativePHP/laravel/assets/40216352/7af57401-534f-4c72-82aa-9b09adeb954e)

**Comment by arif98741** [comment]
> > Got same issue **Platform** `Windows 11` `PHP 8.1` `Laravel 10.15.0`
> > ![Screenshot_153](https://user-images.githubusercontent.com/17213478/254995961-fe65234f-288d-4ccd-bfca-c78763a32691.png)
> 
> Me also getting the same error. So I went to symphony Process.php and manually set tty to false. Next it was showing Starting NativePHP app… but app never running or opening up.
> 
> ![image](https://user-images.githubusercontent.com/17490342/255073467-7e0175a4-3b47-4357-a11e-2389da65e7c3.png)

Yes. I also do.some changes. But no benefit

**Comment by Mohsen-mhm** [comment]
> NativePHP is currently only for macOS

**Comment by diudiudiuu** [comment]
![download](https://github.com/NativePHP/laravel/assets/31238774/4ad636cd-0674-4de9-b6a8-fcf3dd109f40)

只能用WSL试试了

**Comment by arif98741** [comment]
> NativePHP is only for macOS right now, right?

yes

**Comment by lepresk** [comment]
But why it is only for macos loll!!!! 

![Capture](https://github.com/NativePHP/laravel/assets/10780686/00a8169d-545e-4814-af38-f7e72bfae806)

**Comment by Mohsen-mhm** [comment]
It was disappointing, however, we are waiting for Windows support😎👌

**Comment by ahmedtofaha10** [comment]
Disappointed 😔

**Comment by rajibbinalam** [comment]
So, this is not for poor guys like me as a windows OS user right now. right?

**Comment by arif98741** [comment]
> So, this is not for poor guys like me as a windows OS user right now. right?

Yeh. It's their idea regarding win users 🤐

**Comment by simonhamp** [comment]
Windows support is coming. Free and open source software here folks, we're doing our best to get this out to you all as fast we can

Thanks for your support and patience 🙏🏼

**Comment by elhadiabdallah** [comment]
what about linux users :) ?

**Comment by JulitoM3** [comment]
> what about linux users :) ?
Linux support is coming in few weeks

**Comment by drhoussem** [comment]
Got the same error

**Comment by NpaBackend** [comment]
Можно как то костыльно запускать его для windows?

**Comment by fahim27** [comment]
Got the same issue 

![image](https://github.com/NativePHP/laravel/assets/54712723/605718db-d309-45e0-87e6-b0905fdb73de)

**Comment by MotionPhix** [comment]
> Windows support is coming. Free and open source software here folks, we're doing our best to get this out to you all as fast we can
> 
> Thanks for your support and patience 🙏🏼

It would be very wise and save us time from trying things that won't work if you could mention that on in your docs so that people should try out of their own curiosity, not because you want more people to download it and start writing issues here, which, in true sense, are not issues at all. Just mention it in your docs, please. I was about to add it in a project that I had done half way, but an instinct. told me, `No, let me create a new project`. That's how I got saved from total dilemma.

**Comment by Rahisaiful** [comment]
Development server starts on Windows 10, But the Desktop window does not open.


![Screenshot_1](https://github.com/NativePHP/laravel/assets/13090193/ca5b018e-cf42-404c-a3c8-83bf6f2e5b2b)

**Comment by lepresk** [comment]
Try this gist : https://gist.github.com/ShaneShipston/8bb7cabc423cf0cc64da0eacafa53171

**Comment by arif98741** [comment]
After exploring its worked. Thanks to https://gist.github.com/ShaneShipston/8bb7cabc423cf0cc64da0eacafa53171
Nativephp takes a lot of storage . As some modifications are done with node_modules, php and vendor . That's why it might be.
Who wants to explore can download this zip [https://we.tl/t-DtMktUiY4Q](https://we.tl/t-DtMktUiY4Q?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

Then run
php artisan native:serve

**Comment by mpociot** [comment]
The TTY mode is now disabled on windows

**Comment by MotionPhix** [comment]
> The TTY mode is now disabled on windows

What does that mean exactly? Can we now run nativephp on Windows or what? Because right now if I run `php artisan native:serve` I get:

```
Starting NativePHP dev server…
Fetching latest dependencies…

Starting NativePHP app…
```

There are no errors but still more no window opens up! I am running Windows 11 on HP Envy x360 Convertible, PHP 8.2, Laravel 10.

**Comment by Cyprien-png** [comment]
> w disabled on windows

Still get this error from `php artisan db` 

![image](https://github.com/NativePHP/laravel/assets/61788240/f987e22e-7987-445f-94a8-5dc8fdf770a1)

**Comment by mdr0414** [comment]
> > w disabled on windows
> 
> Still get this error from `php artisan db`
> 
> ![image](https://private-user-images.githubusercontent.com/61788240/283806732-f987e22e-7987-445f-94a8-5dc8fdf770a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUzNjYsIm5iZiI6MTcwNjE4NTA2NiwicGF0aCI6Ii82MTc4ODI0MC8yODM4MDY3MzItZjk4N2UyMmUtNzk4Ny00NDVmLTk0YTgtNWRjOGZkZjc3MGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZjRlMDE2OWU3ZWJiZTM3MmQzNTJjZDgzMjgzZjgyOWE0N2MzNWIxZTNkOGY1MTRhYmU5MDkxNjE4MGYzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyCZseJp6VMM3eZdw-qMnzCGViUAap7huF-yId6Wf0g)

Same here ... brand new install on Windows 10, php 8.2.4
