### ISSUE TITLE
[Bug]: native:install not working on Linux

### ISSUE THREAD

**Issue by haiderlatitude** [NativePHP/laravel#83]
### What happened?

Error: Command failed: /home/haiderlatitude/Desktop/mynativephpapp/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config
/home/haiderlatitude/Desktop/mynativephpapp/vendor/nativephp/electron/resources/js/resources/php/php: 1: Syntax error: "(" unexpected

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/home/haiderlatitude/Desktop/mynativephpapp/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '',
  stderr: '/home/haiderlatitude/Desktop/mynativephpapp/vendor/nativephp/electron/resources/js/resources/php/php: 1: Syntax error: "(" unexpected\n'
}

### How to reproduce the bug

php artisan native:install

### Package Version

0.3.2 (according to composer.json)

### PHP Version

8.2.8

### Laravel Version

10.16.1

### Node Version

20.2.0

### Which operating systems does with happen with?

Linux

### Notes

I'm having this error for last two days. Recently saw the tweet from this package's owner in which he says something like "this package now runs on linux" and tried again, but only to get this error again.

**Comment by ArtMin96** [comment]
https://github.com/NativePHP/electron/pull/57

**Comment by haiderlatitude** [comment]
I'm sorry I couldn't understand what to do.
