### ISSUE TITLE
[Bug]: Menu `label` item showing as clickable element

### ISSUE THREAD

**Issue by marcreichel** [NativePHP/laravel#86]
### What happened?

When adding a `label` item to a menu, and showing that menu to the application menu or menu bar context menu, that `label` is displayed as a clickable element.

### How to reproduce the bug

Add a `->label()` item to a menu and register the menu or add it as the context menu of the menu bar.

```php
$menu = Menu::new()
    ->label('My label');

MenuBar::create()
    ->withContextMenu($menu);
```

### Package Version

0.2.0

### PHP Version

8.1.17

### Laravel Version

10.16.1

### Node Version

18.16.0

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
I don't quite understand what you're asking here... do you just want to add an item to a menu that isn't interactive at all for the user?

**Comment by mpociot** [comment]
@marcreichel Right, at the moment a "label" behaves just like any regular menu item - it just doesn't have a custom click event attached.
If you want to disable the label, you may use:

```php
Menu::new()
    ->submenu('Submenu',
        Menu::new()
            ->add(
                (new Label('Label'))->enabled(false)
            )
    )
    ->register();
```

<img width="163" alt="image" src="https://github.com/NativePHP/laravel/assets/804684/65af7cfb-e988-4095-81c3-d1a053d9090c">

**Comment by marcreichel** [comment]
@mpociot Thanks for clarifying 👍🏼
