### ISSUE TITLE
[Bug]: MenuBar-App not working when bundled/published

### ISSUE THREAD

**Issue by marcreichel** [NativePHP/laravel#88]
### What happened?

When building a `MenuBar` app without any windows or a dock icon, the app opens as “Window” application including a dock icon but the menu bar icon is missing.

### How to reproduce the bug

1. Add a `MenuBar` inside the `NativeAppServiceProvider` without `->showDockIcon()`.
2. Bundle the app with `php artisan native:publish`.
3. Open the bundled app.

### Package Version

0.2.0

### PHP Version

8.1.17

### Laravel Version

10.16.1

### Node Version

18.16.0

### Which operating systems does with happen with?

macOS

**Comment by modernben** [comment]
Same here

**Comment by simonhamp** [comment]
Closing due to age of issue and because there have been many fixes since the mentioned release.

Please update to the latest version (v0.6.1) and try again.

If you have further issues, please open a new ticket.
