### ISSUE TITLE
[Bug]: `native:build` command failed 

### ISSUE THREAD

**Issue by hasanuzzamanbe** [NativePHP/laravel#91]
### What happened?

`php artisan native:build` command executed 
  laravel/sanctum ....................................................... DONE
  laravel/tinker ........................................................ DONE
  nativephp/electron .................................................... DONE
  nativephp/laravel ..................................................... DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/termwind ................................................... DONE

then exit with this error
 "electron-vite: command not found"

### How to reproduce the bug

1. Install `php artisan native:install`
2. build `php artisan native:build`
  then exit with this error
 "electron-vite: command not found"

### Package Version

0.2.0

### PHP Version

8.1

### Laravel Version

10.10

### Node Version

14.20.1

### Which operating systems does with happen with?

macOS

**Comment by Kuharenko** [comment]
With latest version nativephp/electron (0.3.2) I call:
`php artisan native:build mac`

It generates me .dmg file. 
Also I copied vendor/nativephp/php-bin/bin/mac/arm64 to vendor/nativephp/php-bin/bin/mac/x64

**Comment by hasanuzzamanbe** [comment]
After a quick debugging, I am able to build the package for macOS.
PHP binary for x64 was not present on the path it was looking for. Don't know why it was not created automatically. I copied it from the Linux directory and paste it into the `mac` directory. 
And it works.

<img width="1167" alt="image" src="https://github.com/NativePHP/laravel/assets/43160844/a0519ccf-a647-4f8d-a5a5-987081f506d6">

**Comment by lotestudio** [comment]
Same here...

**Comment by simonhamp** [comment]
>I copied it from the Linux directory and paste it into the mac directory.

I'm not quite sure how this works, but I'd be very cautious about this as the binaries are built for each platform and won't be 100% interchangeable - something you'd absolutely want to avoid when it comes to distributing your app.

@hasanuzzamanbe Based on what you've reported, I'm assuming that you're developing on an Intel Mac... is that correct?

**Comment by eqxDev** [comment]
Same issue here, tried your fix it did actually open this time but with an error
Test.app/Contents/Resources/app.asar.unpacked/resources/php/php EACCES
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Almost worked then!

**Comment by SRWieZ** [comment]
> > With latest version nativephp/electron (0.3.2) I call: `php artisan native:build mac`
> 
> 
> I tried then it throw errors like this
> 
> `Error copying PHP binary Error: ENOENT: no such file or directory, stat '/Volumes/Projects/debugger/vendor/nativephp/php-bin/bin/mac/x64'`
> 
> 
> `Could not resolve "../../resources/php/php?asset&asarUnpack" from "src/main/index.js"`
> 
> 

Just to give my feedback too. I got the same error on Intel Mac. Tried on the last 2 releases, same behavior.

**Comment by kalimputhawala** [comment]
same here

**Comment by hasanuzzamanbe** [comment]
> > I copied it from the Linux directory and paste it into the mac directory.
> 
> I'm not quite sure how this works, but I'd be very cautious about this as the binaries are built for each platform and won't be 100% interchangeable - something you'd absolutely want to avoid when it comes to distributing your app.
> 
> @hasanuzzamanbe Based on what you've reported, I'm assuming that you're developing on an Intel Mac... is that correct?

Sorry it was "Apple M1 Pro" chip

**Comment by code05-hello** [comment]
Yes, Mac based on intel i3 processor

**Comment by avazquez-bit** [comment]
I Have same issue workin on linux an traying to build to linux, win and mac, even wothout parameter the output is the same
![Uploading 2024-04-30_12-22.png…]()

**Comment by avazquez-bit** [comment]
It work, but now i got
![image](https://github.com/NativePHP/laravel/assets/113546539/b0479c95-25a1-443f-bb45-82b9e2fc9b52)

**Comment by simonhamp** [comment]
Please note that you can't build for Mac when you're not on a Mac

**Comment by avazquez-bit** [comment]
I've droped node_modules and vendor folders and reinstall them and it work. then i tried to build for linux and even when the app is created and actually it work, I got next console messages

![image](https://github.com/NativePHP/laravel/assets/113546539/7cef64b7-7143-4725-8084-18b0e6355197)

Now i'll try to build for windows on windows whit this updates

**Comment by simonhamp** [comment]
That seems to be an error within electron-builder. Not sure what it means exactly, but it seems it might be bypass-able (if I'm interpreting the message correctly)

I'll try to replicate it at some point and find a way to bounce past it, but it would be helpful to raise that as a separate issue as it's off-track from this thread.

**Comment by avazquez-bit** [comment]
Ok, I'll put on new one!!!
Thanks

**Comment by simonhamp** [comment]
For everyone else: there have been a load of improvements to NativePHP recently.

Please update to nativephp/electron v0.6 and try again.
