### ISSUE TITLE
[Bug]: [8038:0731/163413.894021:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

### ISSUE THREAD

**Issue by estudyer** [NativePHP/laravel#94]
### What happened?

[8038:0731/163413.894021:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

php artisan native:serve 启动之后，
<img width="1129" alt="image" src="https://github.com/NativePHP/laravel/assets/19887166/3bc4a44f-e809-41bd-9465-3e7b32f52e0d">
就会有一个错误提示 [8038:0731/163413.894021:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

是少安装了什么吗？
<img width="712" alt="image" src="https://github.com/NativePHP/laravel/assets/19887166/3031a46c-43c2-43ae-8d01-1ed28de1b3b0">

### How to reproduce the bug

-

### Package Version

2.0.0---

### PHP Version

8.1.5

### Laravel Version

10.16.1

### Node Version

16.14.2

### Which operating systems does with happen with?

macOS

**Comment by simonhamp** [comment]
Is this error preventing your app from running? It seems to be related only to the dev tools
