### ISSUE TITLE
[Bug]: Getting Error on Windows 11 

### ISSUE THREAD

**Issue by deepaksp** [NativePHP/laravel#95]
### What happened?

I am using laragon and windows 11, when ever I try to run nativephp it throughs an error like the one below.

![Screenshot 2023-07-31 180254](https://github.com/NativePHP/laravel/assets/11506967/6aa09f2f-0c63-4f21-ae2d-27657a8a4fc1)

### How to reproduce the bug

use laragon latest version
add php 8.1 to path
install laravel and nativelaravel

### Package Version

0.3.3

### PHP Version

8.1.10

### Laravel Version

10.10

### Node Version

19.6.1

### Which operating systems does with happen with?

Windows

**Comment by SWEET1S** [comment]
https://gist.github.com/ShaneShipston/8bb7cabc423cf0cc64da0eacafa53171

I found this, idk if works

**Comment by deepaksp** [comment]
it works but i also found a way to solve it

go to electron-builder.js

set target os to win and change binaryArch to x64

go to php.js and do the same thing

and than resource/js/main/index,js

you need to add .exe after PHP

**Comment by SWEET1S** [comment]
Yes, your way is easier and works. The only bad thing is that we are editing the vendor, otherwise I think that they will fix it soon

**Comment by deepaksp** [comment]
yes, I think it will be solved soon.

**Comment by basst85** [comment]
@Giuliano1993 A (temp) fix would be this change:
https://github.com/NativePHP/electron/pull/68/commits/4b316176fdacf1c499d8cf30368f793e420a6712

After changing this file, run ``php artisan native:serve`` again

**Comment by Giuliano1993** [comment]
Yes @basst85 this worked for me! Thanks!

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
