### ISSUE TITLE
[Bug]: Windows install default darwin binary

### ISSUE THREAD

**Issue by andresayac** [NativePHP/laravel#96]
### What happened?

I have used the same project where I had it working, I did the package update, I deleted the vendor folder and generated a composer update then a php artisan native:install and I have presented myself with this problem it seems that by default in windows it is copying the Mac binary

![image](https://github.com/NativePHP/laravel/assets/16548795/74979b30-01cf-4c8f-86ae-f022c3301145)

### How to reproduce the bug

php artisan native:install

### Package Version

0.3.0

### PHP Version

8.2.0

### Laravel Version

10.10

### Node Version

18.16.0

### Which operating systems does with happen with?

Windows

### Notes

By default, Windows is copying the Mac binary.

**Comment by lothereus** [comment]
Check the installed version of your nativephp/electron package : must be 0.2 or later for Windows

**Comment by andresayac** [comment]
I have 
![image](https://github.com/NativePHP/laravel/assets/16548795/f67456e9-35ba-4a76-983d-604b20dee22b)

**Comment by deepaksp** [comment]
yes having the same issue #95

**Comment by basst85** [comment]
Created this pull request to fix this bug:
https://github.com/NativePHP/electron/pull/68

**Comment by andresayac** [comment]
ll be waiting for the release to test

**Comment by FDT2k** [comment]
Same on Archlinux it copies the mac binary. 

Manually copying the php binary has no effect, it's being erased by the mac version on each run

**Comment by MdAnowarHosen** [comment]
I've got same issue!

**Comment by Ali7med** [comment]
it's not fixed yet.

**Comment by andresayac** [comment]
> aún no está arreglado.
the release is missing with the changes

**Comment by bharathvadivel** [comment]
This Worked for me

In reference with [https://github.com/NativePHP/laravel/issues/105](https://github.com/NativePHP/laravel/issues/105)

By [bagusindrayana](https://github.com/bagusindrayana)

Basically electron repo. issue tab has been moved here therefore link is not working.

To fix this visit => vendor\nativephp\electron\resources\js\electron-builder.js

[https://paste.laravel.io/6c7100ed-fc2f-4d27-ad06-060d70e793fd](https://paste.laravel.io/6c7100ed-fc2f-4d27-ad06-060d70e793fd)

Replace this file

now run below command in sequence :-

=> php artisan native:install
=> php artisan native:build win (you will get error a popup click ok and let complete process).
=> php artisan native:serve

Yeah ! you will your app running on windows !

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
