### ISSUE TITLE
[Question]: Are queues supported by NativePHP?

### ISSUE THREAD

**Issue by wardy484** [NativePHP/laravel#97]
### What happened?

Are Laravels queues supported? 

I noticed in the native PHP talk Marcel gave there was mention of support for Queues / Jobs however I've not been able to figure it out myself. 

### How to reproduce the bug

I attempted to use the database queue driver with no luck but if it is supported it'd be great if it was documented somewhere / how it works. 

### Package Version

0.2

### PHP Version

8.2.0

### Laravel Version

10.10

### Node Version

16.14.2

### Which operating systems does with happen with?

macOS

### Notes
Apologies for logging this as a bug but I got a 404 when clicking to add a question.

**Comment by Jonnx** [comment]
I got queues to work in development mode by using the database driver for queues and then running the following commands

1) create the table migration for db queue driver
```bash
php artisan queue:table 
```

2) launch phpnative (which should run migrations and create the table)
```bash
php artisan native:serve
```

3) manually launch the queue workers in native
```bash
php artisan native:queue   
```

not sure if the queue worker will be booted automatically when the app is built, haven't tested it yet

**Comment by mpociot** [comment]
Queues are support, yeah.
We still need to write docs for that 👍

**Comment by cloudstudio** [comment]
hello @Jonnx ! did you make it work with the build ? queues work for me with serve, but when I do the build they stop working :(

**Comment by Jonnx** [comment]
haven't tried using queues in the built version yet, going to wait for the docs to be in place for it as my project does not require queues YET. would be nice but i can work around it so far

**Comment by robindirksen1** [comment]
@mpociot, when is the queue started? After building the application, the scheduler is running, but the queue worker isn't handling it.

Are there any `.env` changes needed (at this moment, it is the default from laravel/laravel)?

During development, it works when running `php artisan native:queue`.

**Comment by simonhamp** [comment]
The docs for queues are [now in place](https://nativephp.com/docs/1/digging-deeper/queues). Please raise any further queries in a new issue or discussion
